const EN_UI_COPY = {
  commonAddedToCart: "Added to cart",
  commonAddToCartFailed: "Could not add to cart — please try again",
  commonAdding: "Adding...",
  commonSelectVariant: "Select variant",
  commonOutOfStock: "Out of stock",
  commonAddToCart: "Add to cart",
  commonEdit: "Edit",
  commonDismiss: "Dismiss",
  commonWhatsApp: "WhatsApp",
  stockAvailableOnRequest: "Available on request",
  stockInStock: "In stock",
  stockBackorderAvailable: "Backorder available",
  stockCountInStock: "{quantity} in stock",

  heroCatalogBadge: "Premium Tech Catalog - 2026",
  heroHeadlineShopSmarter: "Shop Smarter.",
  heroHeadlineSaveMore: "Save More.",
  heroDescription:
    "Discover the best gear for work, gaming and everyday life - mobiles, laptops, monitors, peripherals and accessories, all in one clean catalog.",
  heroExploreDeals: "Explore Deals ->",
  heroBrowseCatalog: "Browse Catalog",
  heroStatsProducts: "Products",
  heroStatsCollections: "Collections",
  heroStatsCategories: "Categories",
  heroStatsWarranty: "Warranty",
  heroWhatsInside: "What's inside",
  heroPresentedClearly: "High-consideration gear, presented clearly.",
  heroCompareSpecs:
    "Compare specs, variants and prices without digging through noise.",
  heroCollectionLabel: "Collection",
  heroView: "View ->",
  heroCatalogLabel: "Catalog",
  heroBrowseAllProducts: "Browse all products",

  flashSaleLabel: "Flash Sale",
  flashSaleDealsEndIn: "Deals end in:",
  flashSaleHrs: "HRS",
  flashSaleMin: "MIN",
  flashSaleSec: "SEC",
  flashSaleShopDeals: "Shop Flash Deals ->",

  brandStripFeaturedBrands: "Featured Brands",
  categoryPillsTitle: "Shop by Category",
  productRailCollection: "Collection",
  productRailViewAll: "View all",

  navSearchPlaceholder: "Search products, brands...",
  navSearchSuggestionsLabel: "Search suggestions",
  navSearchRecoveredSuggestionsLabel: 'Suggestions for "{query}"',
  navSearchNoSuggestions: "No quick suggestions yet",
  navSearchViewAllResults: 'View all results for "{query}"',
  navSearchViewRecoveredResults: 'View results for "{query}"',
  navMenu: "Menu",
  navHome: "Home",
  navShop: "Shop",
  navCollections: "Collections",
  navAccount: "Account",
  navCart: "Cart",
  navCartWithCount: "Cart ({count})",
  sideMenuDescription:
    "Explore mobiles, laptops, monitors, gaming parts, software, audio, and the accessories that complete the setup.",

  cartTitle: "Cart",
  cartSummaryTitle: "Summary",
  cartTableItem: "Item",
  cartTableQuantity: "Quantity",
  cartTablePrice: "Price",
  cartTableTotal: "Total",
  cartGroupItemsCount: "{count} items",
  cartGroupTotal: "Total",
  cartSignInTitle: "Already have an account?",
  cartSignInDescription: "Sign in for a better experience.",
  cartSignInCta: "Sign in ->",
  cartDiscountHide: "Hide",
  cartDiscountAddCodes: "Add Promotion Code(s)",
  cartDiscountPlaceholder: "Promo code",
  cartDiscountApply: "Apply",
  cartDiscountApplied: "Promotions applied:",
  cartCheckoutCta: "Go to checkout ->",
  cartTotalsSubtotalExcludingShippingTaxes: "Subtotal (excl. shipping and taxes)",
  cartTotalsShipping: "Shipping",
  cartTotalsDiscount: "Discount",
  cartTotalsTaxes: "Taxes",
  cartTotalsTotal: "Total",
  cartEmptyTitle: "Your cart is empty",
  cartEmptyDescription:
    "Looks like you haven't added anything yet. Start browsing and find something you'll love.",
  cartEmptyExploreProducts: "Explore products ->",
  miniCartTitle: "Cart",
  miniCartItemsCount: "{count} items",
  miniCartQty: "Qty: {count}",
  miniCartRemove: "Remove",
  miniCartSubtotal: "Subtotal",
  miniCartSubtotalExcludingTaxes: "(excl. taxes)",
  miniCartViewCartCheckout: "View Cart & Checkout ->",
  miniCartEmptyDescription: "Add items to get started",
  metaCartDescription: "View your cart",

  paymentMethodCreditCard: "Credit card",
  paymentMethodPayPal: "PayPal",
  paymentMethodOffline: "Offline payment",
  productPriceFrom: "From ",

  checkoutBackToCart: "Back to shopping cart",
  checkoutBack: "Back",
  metaCheckoutTitle: "Checkout",
  metaCheckoutDescription: "Complete your order.",
  checkoutOrderSummaryTitle: "Order Summary",
  checkoutProgressTitle: "Checkout progress",
  checkoutStepOfTotal: "Step {current} / {total}",
  checkoutStepAddress: "Address",
  checkoutStepDelivery: "Delivery",
  checkoutStepPayment: "Payment",
  checkoutStepReview: "Review",
  checkoutComplete: "Complete",
  checkoutCurrent: "Current",
  checkoutPending: "Pending",
  checkoutAllPrerequisitesReady: "All prerequisites are ready. Review and place your order when ready.",
  checkoutNextRequiredStep: "Next required step: {step}.",
  checkoutContinueToStep: "Continue to {step} ->",
  checkoutAddressTitle: "Shipping Address",
  checkoutShippingAddressSummary: "Shipping Address",
  checkoutContactSummary: "Contact",
  checkoutBillingAddressSummary: "Billing Address",
  checkoutSameAsShipping: "Same as shipping",
  checkoutContinueToDelivery: "Continue to delivery",
  checkoutSavedAddressPrompt: "Hi {name}, do you want to use one of your saved addresses?",
  checkoutChooseAddress: "Choose an address",
  checkoutFieldFirstName: "First name",
  checkoutFieldLastName: "Last name",
  checkoutFieldAddress: "Address",
  checkoutFieldCompany: "Company",
  checkoutFieldPostalCode: "Postal code",
  checkoutFieldCity: "City",
  checkoutFieldCountry: "Country",
  checkoutFieldStateProvince: "State / Province",
  checkoutFieldEmail: "Email",
  checkoutFieldPhone: "Phone",
  checkoutBillingSameAsShipping: "Billing address same as shipping address",
  checkoutDeliveryTitle: "Delivery",
  checkoutShippingMethodTitle: "Shipping method",
  checkoutShippingMethodDescription: "How would you like your order delivered",
  checkoutStoreTitle: "Store",
  checkoutChooseStoreNearYou: "Choose a store near you",
  checkoutPickupOrder: "Pick up your order",
  checkoutContinueToPayment: "Continue to payment",
  checkoutMethod: "Method",
  checkoutPaymentTitle: "Payment",
  checkoutDeliveryRequiredTitle: "Delivery method required",
  checkoutDeliveryRequiredDescription: "Pick a shipping method first, then return to payment.",
  checkoutGoToDelivery: "Go to delivery",
  checkoutPaymentMethodLabel: "Payment method",
  checkoutPaymentDetailsLabel: "Payment details",
  checkoutGiftCard: "Gift card",
  checkoutSelectDeliveryFirst: "Select delivery first",
  checkoutEnterCardDetailsToContinue: "Enter card details to continue",
  checkoutEnterCardDetails: "Enter card details",
  checkoutContinueToReview: "Continue to review",
  checkoutPaymentNextReview: "Next, you will review your order details before placing it.",
  checkoutPaypalConfirmLater: "You'll confirm in PayPal",
  checkoutOfflineCollectedAfterConfirmation: "Payment is collected offline after order confirmation",
  checkoutAnotherStepWillAppear: "Another step will appear",
  checkoutOfflinePaymentDescription: "Place your order now and arrange payment offline after confirmation.",
  checkoutPaymentEnterCardDetailsLabel: "Enter your card details:",
  checkoutPreparingSecureCardForm: "Preparing secure card form...",
  checkoutReviewTitle: "Review",
  checkoutPaymentSummaryStripTitle: "Payment summary",
  checkoutEstimatedConfirmation: "Estimated confirmation",
  checkoutCompletePaymentSetupEstimate: "Complete payment setup to lock this estimate before placing your order.",
  checkoutBeforePlacingOrder: "Before placing your order",
  checkoutNeedToEditSomething: "Need to edit something?",
  reviewEditStepAria: "Edit {label}",
  checkoutAddressDetails: "Address details",
  checkoutDeliveryMethod: "Delivery method",
  checkoutPaymentMethod: "Payment method",
  checkoutTermsAcknowledgement: "By clicking the Place Order button, you confirm that you have read, understand and accept our Terms of Use, Terms of Sale and Returns Policy and acknowledge that you have read our Privacy Policy.",
  checkoutOrderAssuranceTitle: "Order assurance",
  checkoutOfflinePaymentCollectionTitle: "Offline payment collection",
  checkoutOfflinePaymentCollectionDetail: "No online charge is captured in checkout for this method. Payment is collected offline after the order is placed.",
  checkoutSecurePaymentProcessingTitle: "Secure payment processing",
  checkoutSecurePaymentProcessingDetail: "Your payment details are handled by the selected payment provider.",
  checkoutNoHiddenChargesTitle: "No hidden checkout charges",
  checkoutNoHiddenChargesDetail: "Your current totals in the summary are the charges used at order placement.",
  checkoutInstantConfirmationTitle: "Instant confirmation",
  checkoutInstantConfirmationDetail: "A confirmation will be sent to {email} after successful placement.",
  checkoutWhatHappensNextTitle: "What happens next",
  checkoutWhatNextManualStep1: "1. We place your order now and keep payment collection for the offline follow-up step.",
  checkoutWhatNextStandardStep1: "1. We place your order securely with the selected payment method.",
  checkoutWhatNextStep2: "2. You are taken to the order confirmation page right away.",
  checkoutWhatNextManualStep3: "3. We send your confirmation details to {email} so payment can be arranged offline.",
  checkoutWhatNextStep3: "3. We send your confirmation details to {email}.",
  checkoutCompleteSectionToContinue: "Complete {section} to continue",
  checkoutOnceDoneReturnHere: "Once this is done, return here to place your order.",
  checkoutEstimateInstantAfterPlacement: "Usually instant after order placement",
  checkoutEstimateFewMinutes: "Usually within a few minutes",
  checkoutEstimateAfterCardAuthorization: "Usually instant after card authorization",
  checkoutEstimateAfterProviderConfirmation: "Usually instant after provider confirmation",
  checkoutEstimateOfflineFollowUp: "Confirmed first, then collected offline in this environment",
  checkoutSelectPaymentMethod: "Select a payment method",
  checkoutReturnToPaymentChooseMethod: "Return to Payment and choose a payment method before placing your order.",
  checkoutSubmittingSecureOrder: "Submitting your secure order...",
  checkoutCompleteAddressDeliveryBeforeOrder: "Complete address and delivery details before placing your order.",
  checkoutPreparingSecurePaymentSession: "Preparing secure payment session...",
  checkoutLoadingSecureCardForm: "Loading secure card form...",
  checkoutPlacingSecureOrder: "Placing secure order...",
  checkoutPlaceSecureOrder: "Place secure order",
  checkoutSubmittingOfflineOrder: "Submitting your offline order...",
  checkoutCompleteAddressDeliveryBeforeOfflineOrder: "Complete address and delivery details before placing your offline order.",
  checkoutPlacingOfflineOrder: "Placing offline order...",
  checkoutPlaceOfflineOrder: "Place offline order",
  checkoutConfirmingPayPalPayment: "Confirming your PayPal payment...",
  checkoutCompleteAddressDeliveryBeforePayPal: "Complete address and delivery details before paying with PayPal.",
  checkoutPreparingPayPalSession: "Preparing PayPal session...",
  checkoutLoadingPayPalCheckout: "Loading PayPal checkout...",
  checkoutPayPalUnavailable: "PayPal unavailable",
  checkoutPayPalSdkMissing: "Unable to load the PayPal SDK. Check NEXT_PUBLIC_PAYPAL_CLIENT_ID.",
  checkoutLoadingPayPal: "Loading PayPal...",
  checkoutPayPalCancelled: "PayPal payment was cancelled",
  checkoutPreparePaymentFailed: "Unable to prepare payment method. Please try again.",
  checkoutUnableToPlaceOrder: "Unable to place order",
  checkoutPayPalOrderNotFound: "PayPal order not found. Re-select PayPal to create a fresh payment session.",
  checkoutPayPalProcessFailed: "Failed to process PayPal payment",
  checkoutPayPalLoadFailed: "An error occurred while loading PayPal",

  categoryNavFlashDeals: "Flash Deals",
  categoryNavHot: "HOT",
  categoryNavAll: "All ->",

  sidebarCategories: "Categories",
  sidebarAllProducts: "All products",
  sidebarCollections: "Collections",
  storePageSubtitle:
    "Browse the full catalog - mobiles, laptops, gaming, peripherals, software, and accessories.",
  storeSearchResultsTitle: 'Search results for "{query}"',
  storeSearchResultsSubtitle:
    "Smart search currently matches product titles, descriptions, tags, and catalog metadata through the Store API.",
  storeSearchClear: "Clear search",
  storeSearchRecoveryTitle: 'No direct matches for "{query}"',
  storeSearchRecoverySubtitle:
    'Showing results for "{recovered_query}" based on similar shopper searches.',
  storeSearchRecoveryCta: 'Search for "{recovered_query}" directly',
  storeSearchEmptyTitle: 'No matches for "{query}"',
  storeSearchEmptySubtitle:
    "Try broader keywords, a brand name, or browse the catalog instead.",
  storeSortBy: "Sort by",
  storeSortNewest: "Newest",
  storeSortLatestArrivals: "Latest arrivals",
  storeSortPriceLowHigh: "Price: Low -> High",
  storeSortPriceHighLow: "Price: High -> Low",
  storeProductSingular: "product",
  storeProductPlural: "products",
  paginationPreviousPage: "Previous page",
  paginationNextPage: "Next page",
  sidebarPriceRange: "Price range",
  sidebarPriceUnder50: "Under $50",
  sidebarPrice50To100: "$50 - $100",
  sidebarPrice100To250: "$100 - $250",
  sidebarPriceOver250: "Over $250",

  footerHeadline: "Premium gear for work, gaming, and everyday life.",
  footerDescription:
    "Shop hardware, software, and accessories with a faster, cleaner browsing experience.",
  footerBrowseCatalog: "Browse catalog",
  footerMyAccount: "My account",
  footerCategories: "Categories",
  footerCollections: "Collections",
  footerStore: "Store",
  footerAllProducts: "All products",
  footerAccount: "Account",
  footerCart: "Cart",
  footerRightsReserved: "{year} NEXMART. All rights reserved.",
  footerBuiltWith: "Built with Medusa & Next.js",

  collectionsPageSubtitle:
    "Browse curated collection hubs for brands, launches, and standout product groups.",
  metaCollectionsDescription:
    "Browse NEXMART collections to jump into curated brands, categories, and featured product drops.",
  collectionsPageCardFallbackSummary:
    "Explore products from the {title} collection.",
  collectionsPageViewCollection: "View collection",
  collectionsPageEmpty: "No collections are available yet.",

  pageNotFoundTitle: "Page not found",
  pageNotFoundDescription: "The page you tried to access does not exist.",
  pageNotFoundCta: "Go to frontpage",
  cartNotFoundDescription:
    "The cart you tried to access does not exist. Clear your cookies and try again.",
  metaGenericErrorDescription: "Something went wrong",
  metaHomeTitleSuffix: "Tech Store",
  metaHomeDescription:
    "Your destination for mobiles, laptops, gaming gear, accessories and more - fast shipping, great deals.",

  themeToggleLabel: "Toggle color theme",
  themeSwitchToLight: "Switch to light mode",
  themeSwitchToDark: "Switch to dark mode",
  currencySelectDisplay: "Select display currency",
  currencyDisplayOnlyNote: "Display only · prices in ₪",
  toastNotifications: "Notifications",

  categoryPageLabel: "Category",
  categoryPageSubcategories: "Subcategories",
  categoryPageNarrowCatalogFaster: "Narrow the catalog faster",
  categoryPageExploreSection: "Explore products in this section",
  categoryPageSpotlight: "Category spotlight",

  relatedProductsTitle: "Related products",
  relatedProductsSubtitle:
    "You might also want to check out these products.",
  relatedProductsReasonCollection: "Same collection",
  relatedProductsReasonCategory: "Same category",
  relatedProductsReasonTag: "Similar tag",
  relatedProductsReasonMultiSignal: "Strong match",

  productTabsProductInformation: "Product Information",
  productTabsSpecifications: "Specifications",
  productTabsShippingReturns: "Shipping & Returns",
  productTabsMaterial: "Material",
  productTabsCountryOfOrigin: "Country of origin",
  productTabsType: "Type",
  productTabsWeight: "Weight",
  productTabsDimensions: "Dimensions",
  productTabsSelectOptionAbove: "Select an option above",
  productTabsLinkedToVariantOption: "Linked to variant option: {option}",
  productTabsFastDelivery: "Fast delivery",
  productTabsFastDeliveryDescription:
    "Your package will arrive in 3-5 business days at your pick up location or in the comfort of your home.",
  productTabsSimpleExchanges: "Simple exchanges",
  productTabsSimpleExchangesDescription:
    "Is the fit not quite right? No worries - we'll exchange your product for a new one.",
  productTabsEasyReturns: "Easy returns",
  productTabsEasyReturnsDescription:
    "Just return your product and we'll refund your money. No questions asked - we'll do our best to make sure your return is hassle-free.",

  productActionsGuidedPresets: "Guided presets",
  productActionsDefaultSetup: "Default setup",
  productActionsCurrent: "Current",
  productActionsPresetUnavailable:
    "This preset no longer matches an available variant.",
  productActionsDefaultSetupActive: "Default setup active",
  productActionsRecommendedSetupActive: "Recommended setup active",
  productActionsPreferDefaultSetup: "Prefer the default setup?",
  productActionsPreferRecommendedSetup: "Prefer the recommended setup?",
  productActionsActiveSetupDescription:
    "This merchandised setup is currently selected.",
  productActionsRestoreSetupDescription:
    "Restore this one-click setup if you want to return to the recommended starting point.",
  productActionsRestoreDefaultSetup: "Restore default setup",
  productActionsRestoreRecommendedSetup: "Restore recommended setup",
  productActionsQualifiesFreeShipping: "This item qualifies for free shipping",
  productActionsFreeShippingStartsAt: "Free shipping starts at {amount}",
  productActionsAddingReachesThreshold:
    "Adding this item alone reaches the current free-shipping threshold.",
  productActionsSelectionAway:
    "This selection is {amount} away on its own.",
  productActionsSelectVariantCompareThreshold:
    "Select a variant to compare this item against the free-shipping threshold.",
  productActionsQuantity: "Quantity",
  productActionsDecreaseQuantity: "Decrease quantity",
  productActionsIncreaseQuantity: "Increase quantity",
  productActionsOrderOnWhatsApp: "Order on WhatsApp",
  whatsappPreviewTitle: "Review your WhatsApp order",
  whatsappPreviewDescription:
    "Check the generated message before you continue to WhatsApp.",
  whatsappPreviewNumberLabel: "Sending to",
  whatsappPreviewMessageLabel: "Message preview",
  whatsappPreviewCopy: "Copy message",
  whatsappPreviewCopied: "WhatsApp message copied",
  whatsappPreviewCopyFailed: "Could not copy the WhatsApp message",
  whatsappPreviewOpen: "Continue in WhatsApp",
  whatsappMessageSetupLabel: "Setup",
  whatsappCustomerNoteFieldLabel: "Optional note for WhatsApp",
  whatsappCustomerNoteFieldPlaceholder:
    "Add a short request, question, or preferred contact detail",
  whatsappCustomerNoteFieldHint:
    "This note is added to the generated WhatsApp message before you continue.",
  whatsappCustomerNoteMessageLabel: "Note",

  mobileActionsSelectOptions: "Select options",

  promoTopPicksTag: "Top Picks",
  promoTopPicksSubtitle: "Curated selections for every setup",
  promoNewArrivalsTag: "New Arrivals",
  promoNewArrivalsSubtitle: "Fresh drops added every week",
  promoShopCollection: "Shop Collection ->",

  productPreviewDeal: "DEAL",
  productPreviewViewProduct: "View Product ->",

  imageGalleryZoomImageAria: "Zoom image",
  imageGalleryClickToZoom: "Click to zoom",
  imageGalleryCloseAria: "Close",
  imageGalleryPreviousAria: "Previous image",
  imageGalleryNextAria: "Next image",
  imageGalleryProductImageAlt: "Product image {index}",
  imageGalleryThumbnailAlt: "Thumbnail {index}",

  shippingFreeShippingUnlocked: "Free Shipping unlocked!",
  shippingUnlockFreeShipping: "Unlock Free Shipping",
  shippingFreeUnlocked: "Free Shipping unlocked!",
  shippingUnlockFree: "Unlock Free Shipping",
  shippingOnlyAway: "Only {amount} away",
  shippingViewCart: "View cart",
  shippingViewProducts: "View products",
  freeShippingProgressUnlocked: "You unlocked free shipping",
  freeShippingProgressRemaining: "Add {amount} more for free shipping",
  freeShippingProgressThreshold: "Threshold: {amount} based on item subtotal.",
  freeShippingProgressEligible: "Eligible",
  freeShippingProgressContinueShopping: "Continue shopping to unlock it",

  recommendedSetupsQuickSwitch: "Quick Switch",
  recommendedSetupsTitle: "Recommended setups",
  recommendedSetupsDescription:
    "Jump between curated combinations without manually reselecting every option.",
  recommendedSetupsDefaultSetup: "Default setup",
  recommendedSetupsRecommended: "Recommended",
  recommendedSetupsCurrentSetup: "Current setup",
  recommendedSetupsUseDefaultSetup: "Use default setup",
  recommendedSetupsUseRecommendedSetup: "Use recommended setup",
  recommendedSetupsViewThisSetup: "View this setup",
  recommendedSetupsPresetFallback: "Preset",
} as const

type UiCopyKey = keyof typeof EN_UI_COPY

type UiLocale = "en" | "ar" | "he"

const UI_COPY: Record<UiLocale, Record<UiCopyKey, string>> = {
  en: EN_UI_COPY,
  ar: {
    commonAddedToCart: "تمت الإضافة إلى السلة",
    commonAddToCartFailed: "تعذر الإضافة إلى السلة، حاول مرة أخرى",
    commonAdding: "جارٍ الإضافة...",
    commonSelectVariant: "اختر المتغير",
    commonOutOfStock: "غير متوفر",
    commonAddToCart: "أضف إلى السلة",
    commonEdit: "تعديل",
    commonDismiss: "إغلاق",
    commonWhatsApp: "واتساب",
    stockAvailableOnRequest: "متوفر عند الطلب",
    stockInStock: "متوفر في المخزون",
    stockBackorderAvailable: "متاح للطلب المسبق",
    stockCountInStock: "{quantity} متوفر في المخزون",

    heroCatalogBadge: "كتالوج تقني مميز - 2026",
    heroHeadlineShopSmarter: "تسوق بذكاء.",
    heroHeadlineSaveMore: "وفر أكثر.",
    heroDescription:
      "اكتشف أفضل المنتجات للعمل والألعاب والاستخدام اليومي - هواتف، لابتوبات، شاشات، ملحقات وإكسسوارات في كتالوج واضح وسهل.",
    heroExploreDeals: "اكتشف العروض ->",
    heroBrowseCatalog: "تصفح الكتالوج",
    heroStatsProducts: "منتجات",
    heroStatsCollections: "مجموعات",
    heroStatsCategories: "تصنيفات",
    heroStatsWarranty: "ضمان",
    heroWhatsInside: "ماذا يوجد",
    heroPresentedClearly: "منتجات مدروسة مع عرض واضح.",
    heroCompareSpecs:
      "قارن المواصفات والمتغيرات والأسعار بدون تشتيت.",
    heroCollectionLabel: "مجموعة",
    heroView: "عرض ->",
    heroCatalogLabel: "الكتالوج",
    heroBrowseAllProducts: "تصفح كل المنتجات",

    flashSaleLabel: "تخفيضات سريعة",
    flashSaleDealsEndIn: "ينتهي العرض خلال:",
    flashSaleHrs: "ساعة",
    flashSaleMin: "دقيقة",
    flashSaleSec: "ثانية",
    flashSaleShopDeals: "تسوق عروض التخفيض ->",

    brandStripFeaturedBrands: "العلامات المميزة",
    categoryPillsTitle: "تسوق حسب التصنيف",
    productRailCollection: "مجموعة",
    productRailViewAll: "عرض الكل",

    navSearchPlaceholder: "ابحث عن منتجات أو علامات...",
    navSearchSuggestionsLabel: "اقتراحات البحث",
    navSearchRecoveredSuggestionsLabel: 'اقتراحات لـ "{query}"',
    navSearchNoSuggestions: "لا توجد اقتراحات سريعة بعد",
    navSearchViewAllResults: 'عرض كل النتائج عن "{query}"',
    navSearchViewRecoveredResults: 'اعرض نتائج "{query}"',
    navMenu: "القائمة",
    navHome: "الرئيسية",
    navShop: "المتجر",
    navCollections: "المجموعات",
    navAccount: "الحساب",
    navCart: "السلة",
    navCartWithCount: "السلة ({count})",
    sideMenuDescription:
      "استكشف الجوالات واللابتوبات والشاشات وقطع الألعاب والبرامج والصوتيات والإكسسوارات التي تكمل إعدادك.",

    cartTitle: "السلة",
    cartSummaryTitle: "الملخص",
    cartTableItem: "المنتج",
    cartTableQuantity: "الكمية",
    cartTablePrice: "السعر",
    cartTableTotal: "الإجمالي",
    cartGroupItemsCount: "{count} عناصر",
    cartGroupTotal: "الإجمالي",
    cartSignInTitle: "هل لديك حساب بالفعل؟",
    cartSignInDescription: "سجل الدخول لتجربة أفضل.",
    cartSignInCta: "تسجيل الدخول ->",
    cartDiscountHide: "إخفاء",
    cartDiscountAddCodes: "إضافة رمز/أكواد خصم",
    cartDiscountPlaceholder: "رمز الخصم",
    cartDiscountApply: "تطبيق",
    cartDiscountApplied: "العروض المطبقة:",
    cartCheckoutCta: "المتابعة إلى الدفع ->",
    cartTotalsSubtotalExcludingShippingTaxes: "الإجمالي الفرعي (بدون الشحن والضرائب)",
    cartTotalsShipping: "الشحن",
    cartTotalsDiscount: "الخصم",
    cartTotalsTaxes: "الضرائب",
    cartTotalsTotal: "الإجمالي",
    cartEmptyTitle: "سلتك فارغة",
    cartEmptyDescription:
      "يبدو أنك لم تضف أي شيء بعد. ابدأ التصفح وابحث عن شيء يعجبك.",
    cartEmptyExploreProducts: "استكشف المنتجات ->",
    miniCartTitle: "السلة",
    miniCartItemsCount: "{count} عناصر",
    miniCartQty: "الكمية: {count}",
    miniCartRemove: "إزالة",
    miniCartSubtotal: "الإجمالي الفرعي",
    miniCartSubtotalExcludingTaxes: "(بدون الضرائب)",
    miniCartViewCartCheckout: "عرض السلة والمتابعة إلى الدفع ->",
    miniCartEmptyDescription: "أضف منتجات للبدء",
    metaCartDescription: "اعرض سلتك",

    paymentMethodCreditCard: "بطاقة ائتمان",
    paymentMethodPayPal: "باي بال",
    paymentMethodOffline: "دفع غير متصل",
    productPriceFrom: "ابتداء من ",

    checkoutBackToCart: "العودة إلى سلة التسوق",
    checkoutBack: "رجوع",
    metaCheckoutTitle: "إتمام الطلب",
    metaCheckoutDescription: "أكمل طلبك.",
    checkoutOrderSummaryTitle: "ملخص الطلب",
    checkoutProgressTitle: "تقدم الدفع",
    checkoutStepOfTotal: "الخطوة {current} / {total}",
    checkoutStepAddress: "العنوان",
    checkoutStepDelivery: "التوصيل",
    checkoutStepPayment: "الدفع",
    checkoutStepReview: "المراجعة",
    checkoutComplete: "مكتمل",
    checkoutCurrent: "الحالي",
    checkoutPending: "قيد الانتظار",
    checkoutAllPrerequisitesReady: "كل المتطلبات جاهزة. راجع طلبك ثم أكمله عندما تكون مستعدا.",
    checkoutNextRequiredStep: "الخطوة المطلوبة التالية: {step}.",
    checkoutContinueToStep: "المتابعة إلى {step} ->",
    checkoutAddressTitle: "عنوان الشحن",
    checkoutShippingAddressSummary: "عنوان الشحن",
    checkoutContactSummary: "بيانات التواصل",
    checkoutBillingAddressSummary: "عنوان الفوترة",
    checkoutSameAsShipping: "نفس عنوان الشحن",
    checkoutContinueToDelivery: "المتابعة إلى التوصيل",
    checkoutSavedAddressPrompt: "مرحبا {name}، هل تريد استخدام أحد عناوينك المحفوظة؟",
    checkoutChooseAddress: "اختر عنوانا",
    checkoutFieldFirstName: "الاسم الأول",
    checkoutFieldLastName: "اسم العائلة",
    checkoutFieldAddress: "العنوان",
    checkoutFieldCompany: "الشركة",
    checkoutFieldPostalCode: "الرمز البريدي",
    checkoutFieldCity: "المدينة",
    checkoutFieldCountry: "الدولة",
    checkoutFieldStateProvince: "الولاية / المنطقة",
    checkoutFieldEmail: "البريد الإلكتروني",
    checkoutFieldPhone: "الهاتف",
    checkoutBillingSameAsShipping: "عنوان الفوترة هو نفسه عنوان الشحن",
    checkoutDeliveryTitle: "التوصيل",
    checkoutShippingMethodTitle: "طريقة الشحن",
    checkoutShippingMethodDescription: "كيف تفضل استلام طلبك؟",
    checkoutStoreTitle: "المتجر",
    checkoutChooseStoreNearYou: "اختر متجرا قريبا منك",
    checkoutPickupOrder: "استلام الطلب من المتجر",
    checkoutContinueToPayment: "المتابعة إلى الدفع",
    checkoutMethod: "الطريقة",
    checkoutPaymentTitle: "الدفع",
    checkoutDeliveryRequiredTitle: "مطلوب اختيار طريقة التوصيل",
    checkoutDeliveryRequiredDescription: "اختر طريقة شحن أولا ثم عد إلى خطوة الدفع.",
    checkoutGoToDelivery: "الانتقال إلى التوصيل",
    checkoutPaymentMethodLabel: "طريقة الدفع",
    checkoutPaymentDetailsLabel: "تفاصيل الدفع",
    checkoutGiftCard: "بطاقة هدية",
    checkoutSelectDeliveryFirst: "اختر التوصيل أولا",
    checkoutEnterCardDetailsToContinue: "أدخل بيانات البطاقة للمتابعة",
    checkoutEnterCardDetails: "أدخل بيانات البطاقة",
    checkoutContinueToReview: "المتابعة إلى المراجعة",
    checkoutPaymentNextReview: "بعد ذلك ستراجع تفاصيل الطلب قبل إتمامه.",
    checkoutPaypalConfirmLater: "ستؤكد الدفع داخل باي بال",
    checkoutOfflineCollectedAfterConfirmation: "يتم تحصيل الدفع لاحقا بعد تأكيد الطلب",
    checkoutAnotherStepWillAppear: "ستظهر خطوة إضافية لاحقا",
    checkoutOfflinePaymentDescription: "أكمل طلبك الآن ورتب الدفع لاحقا بعد التأكيد.",
    checkoutPaymentEnterCardDetailsLabel: "أدخل بيانات بطاقتك:",
    checkoutPreparingSecureCardForm: "جارٍ تجهيز نموذج البطاقة الآمن...",
    checkoutReviewTitle: "المراجعة",
    checkoutPaymentSummaryStripTitle: "ملخص الدفع",
    checkoutEstimatedConfirmation: "وقت التأكيد المتوقع",
    checkoutCompletePaymentSetupEstimate: "أكمل إعداد الدفع لتأكيد هذا التوقيت قبل إتمام الطلب.",
    checkoutBeforePlacingOrder: "قبل إتمام الطلب",
    checkoutNeedToEditSomething: "هل تحتاج إلى تعديل شيء؟",
    reviewEditStepAria: "تعديل {label}",
    checkoutAddressDetails: "بيانات العنوان",
    checkoutDeliveryMethod: "طريقة التوصيل",
    checkoutPaymentMethod: "طريقة الدفع",
    checkoutTermsAcknowledgement: "بالنقر على زر إتمام الطلب، فإنك تؤكد أنك قرأت وفهمت ووافقت على شروط الاستخدام وشروط البيع وسياسة الإرجاع، كما تقر بأنك قرأت سياسة الخصوصية الخاصة بنا.",
    checkoutOrderAssuranceTitle: "ضمان الطلب",
    checkoutOfflinePaymentCollectionTitle: "تحصيل الدفع لاحقا",
    checkoutOfflinePaymentCollectionDetail: "لن يتم خصم أي مبلغ إلكترونيا أثناء الدفع لهذه الطريقة. يتم تحصيل الدفع لاحقا بعد إنشاء الطلب.",
    checkoutSecurePaymentProcessingTitle: "معالجة دفع آمنة",
    checkoutSecurePaymentProcessingDetail: "تتم معالجة بيانات الدفع الخاصة بك بواسطة مزود الدفع المختار.",
    checkoutNoHiddenChargesTitle: "لا توجد رسوم خفية",
    checkoutNoHiddenChargesDetail: "الإجماليات الحالية في الملخص هي الرسوم المستخدمة عند إنشاء الطلب.",
    checkoutInstantConfirmationTitle: "تأكيد فوري",
    checkoutInstantConfirmationDetail: "سيتم إرسال تأكيد إلى {email} بعد إتمام الطلب بنجاح.",
    checkoutWhatHappensNextTitle: "ماذا يحدث بعد ذلك",
    checkoutWhatNextManualStep1: "1. ننشئ طلبك الآن ونؤجل تحصيل الدفع إلى خطوة المتابعة غير المتصلة.",
    checkoutWhatNextStandardStep1: "1. ننشئ طلبك بأمان باستخدام طريقة الدفع المحددة.",
    checkoutWhatNextStep2: "2. سيتم نقلك مباشرة إلى صفحة تأكيد الطلب.",
    checkoutWhatNextManualStep3: "3. نرسل تفاصيل التأكيد إلى {email} ليتم ترتيب الدفع لاحقا.",
    checkoutWhatNextStep3: "3. نرسل تفاصيل التأكيد إلى {email}.",
    checkoutCompleteSectionToContinue: "أكمل {section} للمتابعة",
    checkoutOnceDoneReturnHere: "بعد إكمال ذلك، عد إلى هنا لإتمام طلبك.",
    checkoutEstimateInstantAfterPlacement: "عادة يتم التأكيد مباشرة بعد إنشاء الطلب",
    checkoutEstimateFewMinutes: "عادة خلال بضع دقائق",
    checkoutEstimateAfterCardAuthorization: "عادة مباشرة بعد اعتماد البطاقة",
    checkoutEstimateAfterProviderConfirmation: "عادة مباشرة بعد تأكيد المزود",
    checkoutEstimateOfflineFollowUp: "يتم التأكيد أولا ثم تحصيل الدفع لاحقا في هذه البيئة",
    checkoutSelectPaymentMethod: "اختر طريقة دفع",
    checkoutReturnToPaymentChooseMethod: "عد إلى خطوة الدفع واختر طريقة دفع قبل إتمام الطلب.",
    checkoutSubmittingSecureOrder: "جارٍ إرسال طلبك الآمن...",
    checkoutCompleteAddressDeliveryBeforeOrder: "أكمل بيانات العنوان والتوصيل قبل إتمام الطلب.",
    checkoutPreparingSecurePaymentSession: "جارٍ تجهيز جلسة الدفع الآمنة...",
    checkoutLoadingSecureCardForm: "جارٍ تحميل نموذج البطاقة الآمن...",
    checkoutPlacingSecureOrder: "جارٍ إتمام الطلب الآمن...",
    checkoutPlaceSecureOrder: "إتمام الطلب الآمن",
    checkoutSubmittingOfflineOrder: "جارٍ إرسال الطلب غير المتصل...",
    checkoutCompleteAddressDeliveryBeforeOfflineOrder: "أكمل بيانات العنوان والتوصيل قبل إتمام طلب الدفع غير المتصل.",
    checkoutPlacingOfflineOrder: "جارٍ إتمام طلب الدفع غير المتصل...",
    checkoutPlaceOfflineOrder: "إتمام طلب الدفع غير المتصل",
    checkoutConfirmingPayPalPayment: "جارٍ تأكيد دفع باي بال...",
    checkoutCompleteAddressDeliveryBeforePayPal: "أكمل بيانات العنوان والتوصيل قبل الدفع عبر باي بال.",
    checkoutPreparingPayPalSession: "جارٍ تجهيز جلسة باي بال...",
    checkoutLoadingPayPalCheckout: "جارٍ تحميل دفع باي بال...",
    checkoutPayPalUnavailable: "باي بال غير متاح",
    checkoutPayPalSdkMissing: "تعذر تحميل مكتبة باي بال. تحقق من NEXT_PUBLIC_PAYPAL_CLIENT_ID.",
    checkoutLoadingPayPal: "جارٍ تحميل باي بال...",
    checkoutPayPalCancelled: "تم إلغاء دفع باي بال",
    checkoutPreparePaymentFailed: "تعذر تجهيز طريقة الدفع. يرجى المحاولة مرة أخرى.",
    checkoutUnableToPlaceOrder: "تعذر إتمام الطلب",
    checkoutPayPalOrderNotFound: "تعذر العثور على طلب باي بال. أعد اختيار باي بال لإنشاء جلسة دفع جديدة.",
    checkoutPayPalProcessFailed: "فشل في معالجة دفع باي بال",
    checkoutPayPalLoadFailed: "حدث خطأ أثناء تحميل باي بال",

    categoryNavFlashDeals: "عروض سريعة",
    categoryNavHot: "ساخن",
    categoryNavAll: "الكل ->",

    sidebarCategories: "التصنيفات",
    sidebarAllProducts: "كل المنتجات",
    sidebarCollections: "المجموعات",
    storePageSubtitle:
      "تصفح الكتالوج الكامل - الجوالات وأجهزة اللابتوب والألعاب والملحقات الطرفية والبرامج والإكسسوارات.",
    storeSearchResultsTitle: 'نتائج البحث عن "{query}"',
    storeSearchResultsSubtitle:
      "يعتمد البحث الذكي حاليًا على عناوين المنتجات وأوصافها والوسوم وبيانات الكتالوج من واجهة المتجر.",
    storeSearchClear: "مسح البحث",
    storeSearchRecoveryTitle: 'لا توجد مطابقة مباشرة لـ "{query}"',
    storeSearchRecoverySubtitle:
      'نعرض نتائج لـ "{recovered_query}" بناءً على عمليات بحث مشابهة من المتسوقين.',
    storeSearchRecoveryCta: 'ابحث مباشرة عن "{recovered_query}"',
    storeSearchEmptyTitle: 'لا توجد نتائج لـ "{query}"',
    storeSearchEmptySubtitle:
      "جرّب كلمات أوسع أو اسم علامة تجارية أو تصفح الكتالوج مباشرة.",
    storeSortBy: "الترتيب حسب",
    storeSortNewest: "الأحدث",
    storeSortLatestArrivals: "أحدث الإضافات",
    storeSortPriceLowHigh: "السعر: من الأقل إلى الأعلى",
    storeSortPriceHighLow: "السعر: من الأعلى إلى الأقل",
    storeProductSingular: "منتج",
    storeProductPlural: "منتجات",
    paginationPreviousPage: "الصفحة السابقة",
    paginationNextPage: "الصفحة التالية",
    sidebarPriceRange: "نطاق السعر",
    sidebarPriceUnder50: "أقل من $50",
    sidebarPrice50To100: "$50 - $100",
    sidebarPrice100To250: "$100 - $250",
    sidebarPriceOver250: "أكثر من $250",

    footerHeadline: "معدات مميزة للعمل والألعاب والاستخدام اليومي.",
    footerDescription:
      "تسوق الأجهزة والبرامج والإكسسوارات بتجربة أسرع وأكثر وضوحا.",
    footerBrowseCatalog: "تصفح الكتالوج",
    footerMyAccount: "حسابي",
    footerCategories: "التصنيفات",
    footerCollections: "المجموعات",
    footerStore: "المتجر",
    footerAllProducts: "كل المنتجات",
    footerAccount: "الحساب",
    footerCart: "السلة",
    footerRightsReserved: "{year} NEXMART. جميع الحقوق محفوظة.",
    footerBuiltWith: "مبني باستخدام Medusa و Next.js",

    collectionsPageSubtitle:
      "تصفح مجموعات منسقة للعلامات التجارية والإطلاقات ومجموعات المنتجات البارزة.",
    metaCollectionsDescription:
      "تصفح مجموعات NEXMART للوصول إلى العلامات والتصنيفات والإطلاقات المميزة.",
    collectionsPageCardFallbackSummary:
      "استكشف منتجات مجموعة {title}.",
    collectionsPageViewCollection: "عرض المجموعة",
    collectionsPageEmpty: "لا توجد مجموعات متاحة بعد.",

    pageNotFoundTitle: "الصفحة غير موجودة",
    pageNotFoundDescription: "الصفحة التي حاولت الوصول إليها غير موجودة.",
    pageNotFoundCta: "الذهاب إلى الصفحة الرئيسية",
    cartNotFoundDescription:
      "السلة التي حاولت الوصول إليها غير موجودة. امسح ملفات تعريف الارتباط ثم حاول مرة أخرى.",
    metaGenericErrorDescription: "حدث خطأ ما",
    metaHomeTitleSuffix: "متجر التقنية",
    metaHomeDescription:
      "وجهتك للجوالات واللابتوبات ومعدات الألعاب والإكسسوارات والمزيد - شحن سريع وعروض قوية.",

    themeToggleLabel: "تبديل مظهر الألوان",
    themeSwitchToLight: "التبديل إلى الوضع الفاتح",
    themeSwitchToDark: "التبديل إلى الوضع الداكن",
    currencySelectDisplay: "اختر عملة العرض",
    currencyDisplayOnlyNote: "للعرض فقط · الأسعار تبقى بالشيكل ₪",
    toastNotifications: "الإشعارات",

    categoryPageLabel: "الفئة",
    categoryPageSubcategories: "الفئات الفرعية",
    categoryPageNarrowCatalogFaster: "ضيّق نطاق الكتالوج بشكل أسرع",
    categoryPageExploreSection: "استكشف المنتجات في هذا القسم",
    categoryPageSpotlight: "واجهة الفئة",

    relatedProductsTitle: "منتجات ذات صلة",
    relatedProductsSubtitle: "قد ترغب أيضا في الاطلاع على هذه المنتجات.",
    relatedProductsReasonCollection: "من نفس المجموعة",
    relatedProductsReasonCategory: "من نفس الفئة",
    relatedProductsReasonTag: "وسم مشابه",
    relatedProductsReasonMultiSignal: "تطابق قوي",

    productTabsProductInformation: "معلومات المنتج",
    productTabsSpecifications: "المواصفات",
    productTabsShippingReturns: "الشحن والإرجاع",
    productTabsMaterial: "الخامة",
    productTabsCountryOfOrigin: "بلد المنشأ",
    productTabsType: "النوع",
    productTabsWeight: "الوزن",
    productTabsDimensions: "الأبعاد",
    productTabsSelectOptionAbove: "اختر خيارا من الأعلى",
    productTabsLinkedToVariantOption: "مرتبط بخيار المتغير: {option}",
    productTabsFastDelivery: "توصيل سريع",
    productTabsFastDeliveryDescription:
      "سيصل طلبك خلال 3-5 أيام عمل إلى نقطة الاستلام أو إلى منزلك.",
    productTabsSimpleExchanges: "استبدال سهل",
    productTabsSimpleExchangesDescription:
      "المقاس غير مناسب؟ لا مشكلة - سنستبدل المنتج بآخر جديد.",
    productTabsEasyReturns: "إرجاع سهل",
    productTabsEasyReturnsDescription:
      "أعد المنتج وسنعيد لك المبلغ. بدون تعقيدات - سنجعل عملية الإرجاع سهلة.",

    productActionsGuidedPresets: "إعدادات موجهة",
    productActionsDefaultSetup: "الإعداد الافتراضي",
    productActionsCurrent: "الحالي",
    productActionsPresetUnavailable: "هذا الإعداد لا يطابق خيارا متاحا حاليا.",
    productActionsDefaultSetupActive: "الإعداد الافتراضي مفعل",
    productActionsRecommendedSetupActive: "الإعداد المقترح مفعل",
    productActionsPreferDefaultSetup: "تفضل الإعداد الافتراضي؟",
    productActionsPreferRecommendedSetup: "تفضل الإعداد المقترح؟",
    productActionsActiveSetupDescription: "هذا الإعداد التسويقي محدد حاليا.",
    productActionsRestoreSetupDescription:
      "استعد هذا الإعداد بضغطة واحدة للعودة إلى نقطة البداية المقترحة.",
    productActionsRestoreDefaultSetup: "استعد الإعداد الافتراضي",
    productActionsRestoreRecommendedSetup: "استعد الإعداد المقترح",
    productActionsQualifiesFreeShipping: "هذا المنتج يؤهلك للشحن المجاني",
    productActionsFreeShippingStartsAt: "الشحن المجاني يبدأ من {amount}",
    productActionsAddingReachesThreshold:
      "إضافة هذا المنتج وحده تحقق حد الشحن المجاني الحالي.",
    productActionsSelectionAway: "هذا الاختيار يبعد {amount} بمفرده.",
    productActionsSelectVariantCompareThreshold:
      "اختر متغيرا لمقارنة هذا المنتج بحد الشحن المجاني.",
    productActionsQuantity: "الكمية",
    productActionsDecreaseQuantity: "تقليل الكمية",
    productActionsIncreaseQuantity: "زيادة الكمية",
    productActionsOrderOnWhatsApp: "اطلب عبر واتساب",
    whatsappPreviewTitle: "راجع طلبك عبر واتساب",
    whatsappPreviewDescription:
      "تحقق من الرسالة التي تم إنشاؤها قبل المتابعة إلى واتساب.",
    whatsappPreviewNumberLabel: "الإرسال إلى",
    whatsappPreviewMessageLabel: "معاينة الرسالة",
    whatsappPreviewCopy: "نسخ الرسالة",
    whatsappPreviewCopied: "تم نسخ رسالة واتساب",
    whatsappPreviewCopyFailed: "تعذر نسخ رسالة واتساب",
    whatsappPreviewOpen: "المتابعة إلى واتساب",
    whatsappMessageSetupLabel: "الإعداد",
    whatsappCustomerNoteFieldLabel: "ملاحظة اختيارية لواتساب",
    whatsappCustomerNoteFieldPlaceholder:
      "أضف طلباً قصيراً أو سؤالاً أو وسيلة تواصل مفضلة",
    whatsappCustomerNoteFieldHint:
      "ستضاف هذه الملاحظة إلى رسالة واتساب التي يتم إنشاؤها قبل المتابعة.",
    whatsappCustomerNoteMessageLabel: "ملاحظة",

    mobileActionsSelectOptions: "اختر الخيارات",

    promoTopPicksTag: "أفضل الاختيارات",
    promoTopPicksSubtitle: "مختارات مميزة لكل إعداد",
    promoNewArrivalsTag: "وصل حديثا",
    promoNewArrivalsSubtitle: "إضافات جديدة كل أسبوع",
    promoShopCollection: "تسوق المجموعة ->",

    productPreviewDeal: "عرض",
    productPreviewViewProduct: "عرض المنتج ->",

    imageGalleryZoomImageAria: "تكبير الصورة",
    imageGalleryClickToZoom: "انقر للتكبير",
    imageGalleryCloseAria: "إغلاق",
    imageGalleryPreviousAria: "الصورة السابقة",
    imageGalleryNextAria: "الصورة التالية",
    imageGalleryProductImageAlt: "صورة المنتج {index}",
    imageGalleryThumbnailAlt: "صورة مصغرة {index}",

    shippingFreeShippingUnlocked: "تم تفعيل الشحن المجاني!",
    shippingUnlockFreeShipping: "احصل على الشحن المجاني",
    shippingFreeUnlocked: "تم تفعيل الشحن المجاني!",
    shippingUnlockFree: "احصل على الشحن المجاني",
    shippingOnlyAway: "متبقي فقط {amount}",
    shippingViewCart: "عرض السلة",
    shippingViewProducts: "عرض المنتجات",
    freeShippingProgressUnlocked: "لقد حصلت على الشحن المجاني",
    freeShippingProgressRemaining: "أضف {amount} أخرى للحصول على الشحن المجاني",
    freeShippingProgressThreshold: "الحد: {amount} بناءً على إجمالي المنتجات.",
    freeShippingProgressEligible: "مؤهل",
    freeShippingProgressContinueShopping: "واصل التسوق للحصول عليه",

    recommendedSetupsQuickSwitch: "تبديل سريع",
    recommendedSetupsTitle: "إعدادات مقترحة",
    recommendedSetupsDescription:
      "انتقل بين التركيبات المقترحة بدون إعادة اختيار كل خيار يدويا.",
    recommendedSetupsDefaultSetup: "الإعداد الافتراضي",
    recommendedSetupsRecommended: "مقترح",
    recommendedSetupsCurrentSetup: "الإعداد الحالي",
    recommendedSetupsUseDefaultSetup: "استخدم الإعداد الافتراضي",
    recommendedSetupsUseRecommendedSetup: "استخدم الإعداد المقترح",
    recommendedSetupsViewThisSetup: "عرض هذا الإعداد",
    recommendedSetupsPresetFallback: "إعداد",
  },
  he: {
    commonAddedToCart: "נוסף לעגלה",
    commonAddToCartFailed: "לא ניתן להוסיף לעגלה, נסו שוב",
    commonAdding: "מוסיף...",
    commonSelectVariant: "בחרו וריאנט",
    commonOutOfStock: "אזל מהמלאי",
    commonAddToCart: "הוסף לעגלה",
    commonEdit: "עריכה",
    commonDismiss: "סגירה",
    commonWhatsApp: "וואטסאפ",
    stockAvailableOnRequest: "זמין לפי בקשה",
    stockInStock: "במלאי",
    stockBackorderAvailable: "זמין להזמנה מוקדמת",
    stockCountInStock: "{quantity} במלאי",

    heroCatalogBadge: "קטלוג טכנולוגיה מובחר - 2026",
    heroHeadlineShopSmarter: "קנו חכם יותר.",
    heroHeadlineSaveMore: "חסכו יותר.",
    heroDescription:
      "גלו את הציוד הטוב ביותר לעבודה, לגיימינג וליומיום - מוביילים, מחשבים ניידים, מסכים, ציוד היקפי ואביזרים, הכל בקטלוג נקי וברור.",
    heroExploreDeals: "גלו מבצעים ->",
    heroBrowseCatalog: "עיון בקטלוג",
    heroStatsProducts: "מוצרים",
    heroStatsCollections: "קולקציות",
    heroStatsCategories: "קטגוריות",
    heroStatsWarranty: "אחריות",
    heroWhatsInside: "מה בפנים",
    heroPresentedClearly: "ציוד משמעותי, מוצג בצורה ברורה.",
    heroCompareSpecs:
      "השוו מפרטים, וריאנטים ומחירים בלי לחפש בתוך עומס.",
    heroCollectionLabel: "קולקציה",
    heroView: "צפייה ->",
    heroCatalogLabel: "קטלוג",
    heroBrowseAllProducts: "צפו בכל המוצרים",

    flashSaleLabel: "מבצע בזק",
    flashSaleDealsEndIn: "המבצע מסתיים בעוד:",
    flashSaleHrs: "שעה",
    flashSaleMin: "דקה",
    flashSaleSec: "שנייה",
    flashSaleShopDeals: "לקניית מבצעי בזק ->",

    brandStripFeaturedBrands: "מותגים מובילים",
    categoryPillsTitle: "קנו לפי קטגוריה",
    productRailCollection: "קולקציה",
    productRailViewAll: "צפו בהכל",

    navSearchPlaceholder: "חפשו מוצרים, מותגים...",
    navSearchSuggestionsLabel: "הצעות חיפוש",
    navSearchRecoveredSuggestionsLabel: 'הצעות עבור "{query}"',
    navSearchNoSuggestions: "אין עדיין הצעות מהירות",
    navSearchViewAllResults: 'הצגת כל התוצאות עבור "{query}"',
    navSearchViewRecoveredResults: 'הצגת תוצאות עבור "{query}"',
    navMenu: "תפריט",
    navHome: "בית",
    navShop: "חנות",
    navCollections: "קולקציות",
    navAccount: "חשבון",
    navCart: "עגלה",
    navCartWithCount: "עגלה ({count})",
    sideMenuDescription:
      "גלו מוביילים, מחשבים ניידים, מסכים, חלקי גיימינג, תוכנה, אודיו והאביזרים שמשלימים את ההגדרה שלכם.",

    cartTitle: "עגלה",
    cartSummaryTitle: "סיכום",
    cartTableItem: "פריט",
    cartTableQuantity: "כמות",
    cartTablePrice: "מחיר",
    cartTableTotal: "סה\"כ",
    cartGroupItemsCount: "{count} פריטים",
    cartGroupTotal: "סה\"כ",
    cartSignInTitle: "כבר יש לכם חשבון?",
    cartSignInDescription: "התחברו לחוויית קנייה טובה יותר.",
    cartSignInCta: "התחברות ->",
    cartDiscountHide: "הסתרה",
    cartDiscountAddCodes: "הוספת קוד/י הטבה",
    cartDiscountPlaceholder: "קוד הטבה",
    cartDiscountApply: "החלה",
    cartDiscountApplied: "הטבות שהוחלו:",
    cartCheckoutCta: "המשך לתשלום ->",
    cartTotalsSubtotalExcludingShippingTaxes: "סכום ביניים (ללא משלוח ומסים)",
    cartTotalsShipping: "משלוח",
    cartTotalsDiscount: "הנחה",
    cartTotalsTaxes: "מסים",
    cartTotalsTotal: "סה\"כ",
    cartEmptyTitle: "העגלה שלכם ריקה",
    cartEmptyDescription:
      "נראה שעדיין לא הוספתם פריטים. התחילו לגלוש ומצאו משהו שתאהבו.",
    cartEmptyExploreProducts: "גלו מוצרים ->",
    miniCartTitle: "עגלה",
    miniCartItemsCount: "{count} פריטים",
    miniCartQty: "כמות: {count}",
    miniCartRemove: "הסרה",
    miniCartSubtotal: "סכום ביניים",
    miniCartSubtotalExcludingTaxes: "(ללא מסים)",
    miniCartViewCartCheckout: "צפייה בעגלה ומעבר לתשלום ->",
    miniCartEmptyDescription: "הוסיפו פריטים כדי להתחיל",
    metaCartDescription: "צפו בעגלה שלכם",

    paymentMethodCreditCard: "כרטיס אשראי",
    paymentMethodPayPal: "PayPal",
    paymentMethodOffline: "תשלום לא מקוון",
    productPriceFrom: "החל מ-",

    checkoutBackToCart: "חזרה לעגלת הקניות",
    checkoutBack: "חזרה",
    metaCheckoutTitle: "תשלום",
    metaCheckoutDescription: "השלימו את ההזמנה שלכם.",
    checkoutOrderSummaryTitle: "סיכום ההזמנה",
    checkoutProgressTitle: "התקדמות התשלום",
    checkoutStepOfTotal: "שלב {current} / {total}",
    checkoutStepAddress: "כתובת",
    checkoutStepDelivery: "משלוח",
    checkoutStepPayment: "תשלום",
    checkoutStepReview: "סקירה",
    checkoutComplete: "הושלם",
    checkoutCurrent: "נוכחי",
    checkoutPending: "ממתין",
    checkoutAllPrerequisitesReady: "כל הדרישות מוכנות. עברו על ההזמנה והשלימו אותה כשתהיו מוכנים.",
    checkoutNextRequiredStep: "השלב הנדרש הבא: {step}.",
    checkoutContinueToStep: "המשך אל {step} ->",
    checkoutAddressTitle: "כתובת משלוח",
    checkoutShippingAddressSummary: "כתובת משלוח",
    checkoutContactSummary: "פרטי קשר",
    checkoutBillingAddressSummary: "כתובת לחיוב",
    checkoutSameAsShipping: "זהה לכתובת המשלוח",
    checkoutContinueToDelivery: "המשך למשלוח",
    checkoutSavedAddressPrompt: "היי {name}, האם תרצו להשתמש באחת מהכתובות השמורות שלכם?",
    checkoutChooseAddress: "בחרו כתובת",
    checkoutFieldFirstName: "שם פרטי",
    checkoutFieldLastName: "שם משפחה",
    checkoutFieldAddress: "כתובת",
    checkoutFieldCompany: "חברה",
    checkoutFieldPostalCode: "מיקוד",
    checkoutFieldCity: "עיר",
    checkoutFieldCountry: "מדינה",
    checkoutFieldStateProvince: "מחוז / אזור",
    checkoutFieldEmail: "אימייל",
    checkoutFieldPhone: "טלפון",
    checkoutBillingSameAsShipping: "כתובת החיוב זהה לכתובת המשלוח",
    checkoutDeliveryTitle: "משלוח",
    checkoutShippingMethodTitle: "שיטת משלוח",
    checkoutShippingMethodDescription: "איך תרצו לקבל את ההזמנה שלכם",
    checkoutStoreTitle: "חנות",
    checkoutChooseStoreNearYou: "בחרו חנות קרובה אליכם",
    checkoutPickupOrder: "איסוף ההזמנה",
    checkoutContinueToPayment: "המשך לתשלום",
    checkoutMethod: "שיטה",
    checkoutPaymentTitle: "תשלום",
    checkoutDeliveryRequiredTitle: "נדרשת שיטת משלוח",
    checkoutDeliveryRequiredDescription: "בחרו קודם שיטת משלוח ואז חזרו לתשלום.",
    checkoutGoToDelivery: "מעבר למשלוח",
    checkoutPaymentMethodLabel: "אמצעי תשלום",
    checkoutPaymentDetailsLabel: "פרטי תשלום",
    checkoutGiftCard: "כרטיס מתנה",
    checkoutSelectDeliveryFirst: "בחרו קודם משלוח",
    checkoutEnterCardDetailsToContinue: "הזינו פרטי כרטיס כדי להמשיך",
    checkoutEnterCardDetails: "הזינו פרטי כרטיס",
    checkoutContinueToReview: "המשך לסקירה",
    checkoutPaymentNextReview: "לאחר מכן תעברו על פרטי ההזמנה לפני ההשלמה.",
    checkoutPaypalConfirmLater: "תאשרו ב-PayPal",
    checkoutOfflineCollectedAfterConfirmation: "התשלום נאסף לאחר אישור ההזמנה",
    checkoutAnotherStepWillAppear: "יופיע שלב נוסף",
    checkoutOfflinePaymentDescription: "בצעו את ההזמנה עכשיו וסדרו את התשלום בהמשך לאחר האישור.",
    checkoutPaymentEnterCardDetailsLabel: "הזינו את פרטי הכרטיס:",
    checkoutPreparingSecureCardForm: "טופס הכרטיס המאובטח בהכנה...",
    checkoutReviewTitle: "סקירה",
    checkoutPaymentSummaryStripTitle: "סיכום תשלום",
    checkoutEstimatedConfirmation: "זמן אישור משוער",
    checkoutCompletePaymentSetupEstimate: "השלימו את הגדרת התשלום כדי לקבע את ההערכה הזו לפני ביצוע ההזמנה.",
    checkoutBeforePlacingOrder: "לפני ביצוע ההזמנה",
    checkoutNeedToEditSomething: "צריכים לערוך משהו?",
    reviewEditStepAria: "עריכת {label}",
    checkoutAddressDetails: "פרטי כתובת",
    checkoutDeliveryMethod: "שיטת משלוח",
    checkoutPaymentMethod: "אמצעי תשלום",
    checkoutTermsAcknowledgement: "בלחיצה על כפתור ביצוע ההזמנה, אתם מאשרים שקראתם, הבנתם וקיבלתם את תנאי השימוש, תנאי המכירה ומדיניות ההחזרות, ומאשרים שקראתם את מדיניות הפרטיות שלנו.",
    checkoutOrderAssuranceTitle: "הבטחת הזמנה",
    checkoutOfflinePaymentCollectionTitle: "איסוף תשלום לא מקוון",
    checkoutOfflinePaymentCollectionDetail: "לא מתבצע חיוב מקוון בקופה עבור שיטה זו. התשלום נאסף לאחר ביצוע ההזמנה.",
    checkoutSecurePaymentProcessingTitle: "עיבוד תשלום מאובטח",
    checkoutSecurePaymentProcessingDetail: "פרטי התשלום שלכם מטופלים על ידי ספק התשלום שנבחר.",
    checkoutNoHiddenChargesTitle: "ללא חיובים נסתרים",
    checkoutNoHiddenChargesDetail: "הסכומים הנוכחיים בסיכום הם החיובים שישמשו בעת יצירת ההזמנה.",
    checkoutInstantConfirmationTitle: "אישור מיידי",
    checkoutInstantConfirmationDetail: "אישור יישלח אל {email} לאחר השלמת ההזמנה בהצלחה.",
    checkoutWhatHappensNextTitle: "מה קורה בהמשך",
    checkoutWhatNextManualStep1: "1. אנחנו מבצעים את ההזמנה עכשיו ומשאירים את גביית התשלום לשלב המעקב הלא מקוון.",
    checkoutWhatNextStandardStep1: "1. אנחנו מבצעים את ההזמנה בצורה מאובטחת עם אמצעי התשלום שנבחר.",
    checkoutWhatNextStep2: "2. תועברו מיד לעמוד אישור ההזמנה.",
    checkoutWhatNextManualStep3: "3. נשלח את פרטי האישור אל {email} כדי שניתן יהיה להסדיר את התשלום בהמשך.",
    checkoutWhatNextStep3: "3. נשלח את פרטי האישור אל {email}.",
    checkoutCompleteSectionToContinue: "השלימו את {section} כדי להמשיך",
    checkoutOnceDoneReturnHere: "לאחר שתשלימו זאת, חזרו לכאן כדי לבצע את ההזמנה.",
    checkoutEstimateInstantAfterPlacement: "בדרך כלל מיד לאחר ביצוע ההזמנה",
    checkoutEstimateFewMinutes: "בדרך כלל בתוך כמה דקות",
    checkoutEstimateAfterCardAuthorization: "בדרך כלל מיד לאחר אישור הכרטיס",
    checkoutEstimateAfterProviderConfirmation: "בדרך כלל מיד לאחר אישור הספק",
    checkoutEstimateOfflineFollowUp: "מאושר קודם ואז נגבה לא מקוון בסביבה הזו",
    checkoutSelectPaymentMethod: "בחרו אמצעי תשלום",
    checkoutReturnToPaymentChooseMethod: "חזרו לתשלום ובחרו אמצעי תשלום לפני ביצוע ההזמנה.",
    checkoutSubmittingSecureOrder: "שולחים את ההזמנה המאובטחת שלכם...",
    checkoutCompleteAddressDeliveryBeforeOrder: "השלימו פרטי כתובת ומשלוח לפני ביצוע ההזמנה.",
    checkoutPreparingSecurePaymentSession: "מכינים סשן תשלום מאובטח...",
    checkoutLoadingSecureCardForm: "טופס הכרטיס המאובטח נטען...",
    checkoutPlacingSecureOrder: "מבצעים הזמנה מאובטחת...",
    checkoutPlaceSecureOrder: "בצעו הזמנה מאובטחת",
    checkoutSubmittingOfflineOrder: "שולחים את ההזמנה הלא מקוונת...",
    checkoutCompleteAddressDeliveryBeforeOfflineOrder: "השלימו פרטי כתובת ומשלוח לפני ביצוע הזמנה לא מקוונת.",
    checkoutPlacingOfflineOrder: "מבצעים הזמנה לא מקוונת...",
    checkoutPlaceOfflineOrder: "בצעו הזמנה לא מקוונת",
    checkoutConfirmingPayPalPayment: "מאשרים את תשלום ה-PayPal שלכם...",
    checkoutCompleteAddressDeliveryBeforePayPal: "השלימו פרטי כתובת ומשלוח לפני תשלום ב-PayPal.",
    checkoutPreparingPayPalSession: "מכינים סשן PayPal...",
    checkoutLoadingPayPalCheckout: "טוענים את תשלום PayPal...",
    checkoutPayPalUnavailable: "PayPal לא זמין",
    checkoutPayPalSdkMissing: "לא ניתן לטעון את SDK של PayPal. בדקו את NEXT_PUBLIC_PAYPAL_CLIENT_ID.",
    checkoutLoadingPayPal: "PayPal נטען...",
    checkoutPayPalCancelled: "תשלום ה-PayPal בוטל",
    checkoutPreparePaymentFailed: "לא ניתן להכין את אמצעי התשלום. נסו שוב.",
    checkoutUnableToPlaceOrder: "לא ניתן לבצע את ההזמנה",
    checkoutPayPalOrderNotFound: "לא נמצאה הזמנת PayPal. בחרו שוב ב-PayPal כדי ליצור סשן תשלום חדש.",
    checkoutPayPalProcessFailed: "עיבוד תשלום ה-PayPal נכשל",
    checkoutPayPalLoadFailed: "אירעה שגיאה בזמן טעינת PayPal",

    categoryNavFlashDeals: "מבצעי בזק",
    categoryNavHot: "חם",
    categoryNavAll: "הכל ->",

    sidebarCategories: "קטגוריות",
    sidebarAllProducts: "כל המוצרים",
    sidebarCollections: "קולקציות",
    storePageSubtitle:
      "עיינו בקטלוג המלא - מוביילים, מחשבים ניידים, גיימינג, ציוד היקפי, תוכנה ואביזרים.",
    storeSearchResultsTitle: 'תוצאות חיפוש עבור "{query}"',
    storeSearchResultsSubtitle:
      "החיפוש החכם משתמש כרגע בכותרות מוצרים, תיאורים, תגיות ומטא-דאטה של הקטלוג דרך Store API.",
    storeSearchClear: "ניקוי חיפוש",
    storeSearchRecoveryTitle: 'לא נמצאה התאמה ישירה עבור "{query}"',
    storeSearchRecoverySubtitle:
      'מוצגות תוצאות עבור "{recovered_query}" על בסיס חיפושים דומים של לקוחות.',
    storeSearchRecoveryCta: 'חפשו ישירות את "{recovered_query}"',
    storeSearchEmptyTitle: 'לא נמצאו תוצאות עבור "{query}"',
    storeSearchEmptySubtitle:
      "נסו מילות מפתח רחבות יותר, שם מותג, או עברו לגלישה בקטלוג.",
    storeSortBy: "מיון לפי",
    storeSortNewest: "החדש ביותר",
    storeSortLatestArrivals: "ההגעות האחרונות",
    storeSortPriceLowHigh: "מחיר: מהנמוך לגבוה",
    storeSortPriceHighLow: "מחיר: מהגבוה לנמוך",
    storeProductSingular: "מוצר",
    storeProductPlural: "מוצרים",
    paginationPreviousPage: "העמוד הקודם",
    paginationNextPage: "העמוד הבא",
    sidebarPriceRange: "טווח מחירים",
    sidebarPriceUnder50: "מתחת ל-$50",
    sidebarPrice50To100: "$50 - $100",
    sidebarPrice100To250: "$100 - $250",
    sidebarPriceOver250: "מעל $250",

    footerHeadline: "ציוד פרימיום לעבודה, לגיימינג וליומיום.",
    footerDescription:
      "קנו חומרה, תוכנה ואביזרים בחוויית גלישה מהירה ונקייה יותר.",
    footerBrowseCatalog: "עיון בקטלוג",
    footerMyAccount: "החשבון שלי",
    footerCategories: "קטגוריות",
    footerCollections: "קולקציות",
    footerStore: "חנות",
    footerAllProducts: "כל המוצרים",
    footerAccount: "חשבון",
    footerCart: "עגלה",
    footerRightsReserved: "{year} NEXMART. כל הזכויות שמורות.",
    footerBuiltWith: "נבנה עם Medusa ו-Next.js",

    collectionsPageSubtitle:
      "עיינו במוקדי קולקציות נבחרים עבור מותגים, השקות וקבוצות מוצרים בולטות.",
    metaCollectionsDescription:
      "עיינו בקולקציות NEXMART כדי לקפוץ למותגים, קטגוריות והשקות בולטות.",
    collectionsPageCardFallbackSummary:
      "גלו מוצרים מתוך קולקציית {title}.",
    collectionsPageViewCollection: "לצפייה בקולקציה",
    collectionsPageEmpty: "עדיין אין קולקציות זמינות.",

    pageNotFoundTitle: "העמוד לא נמצא",
    pageNotFoundDescription: "העמוד שניסיתם לפתוח אינו קיים.",
    pageNotFoundCta: "חזרה לעמוד הבית",
    cartNotFoundDescription:
      "העגלה שניסיתם לפתוח אינה קיימת. נקו את העוגיות ונסו שוב.",
    metaGenericErrorDescription: "משהו השתבש",
    metaHomeTitleSuffix: "חנות טכנולוגיה",
    metaHomeDescription:
      "היעד שלכם למוביילים, מחשבים ניידים, ציוד גיימינג, אביזרים ועוד - משלוח מהיר ומבצעים מצוינים.",

    themeToggleLabel: "החלפת ערכת צבעים",
    themeSwitchToLight: "מעבר למצב בהיר",
    themeSwitchToDark: "מעבר למצב כהה",
    currencySelectDisplay: "בחירת מטבע תצוגה",
    currencyDisplayOnlyNote: "לתצוגה בלבד · המחירים נשארים ב-₪",
    toastNotifications: "התראות",

    categoryPageLabel: "קטגוריה",
    categoryPageSubcategories: "תתי-קטגוריות",
    categoryPageNarrowCatalogFaster: "צמצמו את הקטלוג מהר יותר",
    categoryPageExploreSection: "גלו מוצרים בקטגוריה הזו",
    categoryPageSpotlight: "זרקור על הקטגוריה",

    relatedProductsTitle: "מוצרים קשורים",
    relatedProductsSubtitle: "אולי תרצו לבדוק גם את המוצרים האלו.",
    relatedProductsReasonCollection: "מאותה קולקציה",
    relatedProductsReasonCategory: "מאותה קטגוריה",
    relatedProductsReasonTag: "תגית דומה",
    relatedProductsReasonMultiSignal: "התאמה חזקה",

    productTabsProductInformation: "מידע על המוצר",
    productTabsSpecifications: "מפרט",
    productTabsShippingReturns: "משלוח והחזרות",
    productTabsMaterial: "חומר",
    productTabsCountryOfOrigin: "ארץ מקור",
    productTabsType: "סוג",
    productTabsWeight: "משקל",
    productTabsDimensions: "מידות",
    productTabsSelectOptionAbove: "בחרו אפשרות למעלה",
    productTabsLinkedToVariantOption: "מקושר לאפשרות וריאנט: {option}",
    productTabsFastDelivery: "משלוח מהיר",
    productTabsFastDeliveryDescription:
      "החבילה שלכם תגיע תוך 3-5 ימי עסקים לנקודת האיסוף או עד הבית.",
    productTabsSimpleExchanges: "החלפות פשוטות",
    productTabsSimpleExchangesDescription:
      "המידה לא מתאימה? אין בעיה - נחליף את המוצר בחדש.",
    productTabsEasyReturns: "החזרות קלות",
    productTabsEasyReturnsDescription:
      "פשוט החזירו את המוצר ונחזיר את כספכם. בלי שאלות - נעשה הכל כדי שההחזרה תהיה קלה.",

    productActionsGuidedPresets: "הגדרות מודרכות",
    productActionsDefaultSetup: "הגדרת ברירת מחדל",
    productActionsCurrent: "נוכחי",
    productActionsPresetUnavailable:
      "ההגדרה הזו כבר לא תואמת וריאנט זמין.",
    productActionsDefaultSetupActive: "הגדרת ברירת מחדל פעילה",
    productActionsRecommendedSetupActive: "הגדרה מומלצת פעילה",
    productActionsPreferDefaultSetup: "להעדיף את הגדרת ברירת המחדל?",
    productActionsPreferRecommendedSetup: "להעדיף את ההגדרה המומלצת?",
    productActionsActiveSetupDescription: "ההגדרה המסחרית הזו נבחרה כרגע.",
    productActionsRestoreSetupDescription:
      "שחזרו את ההגדרה בלחיצה אחת כדי לחזור לנקודת ההתחלה המומלצת.",
    productActionsRestoreDefaultSetup: "שחזר הגדרת ברירת מחדל",
    productActionsRestoreRecommendedSetup: "שחזר הגדרה מומלצת",
    productActionsQualifiesFreeShipping: "המוצר הזה מזכה במשלוח חינם",
    productActionsFreeShippingStartsAt: "משלוח חינם מתחיל ב-{amount}",
    productActionsAddingReachesThreshold:
      "הוספת הפריט הזה לבדו מגיעה לסף המשלוח החינמי.",
    productActionsSelectionAway: "הבחירה הזו רחוקה ב-{amount} בפני עצמה.",
    productActionsSelectVariantCompareThreshold:
      "בחרו וריאנט כדי להשוות את הפריט הזה לסף משלוח חינם.",
    productActionsQuantity: "כמות",
    productActionsDecreaseQuantity: "הקטן כמות",
    productActionsIncreaseQuantity: "הגדל כמות",
    productActionsOrderOnWhatsApp: "הזמנה בוואטסאפ",
    whatsappPreviewTitle: "עברו על ההזמנה בוואטסאפ",
    whatsappPreviewDescription:
      "בדקו את ההודעה שנוצרה לפני שאתם ממשיכים לוואטסאפ.",
    whatsappPreviewNumberLabel: "נשלח אל",
    whatsappPreviewMessageLabel: "תצוגת הודעה",
    whatsappPreviewCopy: "העתקת הודעה",
    whatsappPreviewCopied: "הודעת הוואטסאפ הועתקה",
    whatsappPreviewCopyFailed: "לא ניתן היה להעתיק את הודעת הוואטסאפ",
    whatsappPreviewOpen: "המשך בוואטסאפ",
    whatsappMessageSetupLabel: "הגדרה",
    whatsappCustomerNoteFieldLabel: "הערה אופציונלית לוואטסאפ",
    whatsappCustomerNoteFieldPlaceholder:
      "הוסיפו בקשה קצרה, שאלה או פרטי קשר מועדפים",
    whatsappCustomerNoteFieldHint:
      "ההערה הזו תתווסף להודעת הוואטסאפ שנוצרת לפני ההמשך.",
    whatsappCustomerNoteMessageLabel: "הערה",

    mobileActionsSelectOptions: "בחרו אפשרויות",

    promoTopPicksTag: "בחירות מובילות",
    promoTopPicksSubtitle: "מבחרים מותאמים לכל תצורה",
    promoNewArrivalsTag: "חדש בחנות",
    promoNewArrivalsSubtitle: "מוצרים חדשים מתווספים כל שבוע",
    promoShopCollection: "לצפייה בקולקציה ->",

    productPreviewDeal: "מבצע",
    productPreviewViewProduct: "לצפייה במוצר ->",

    imageGalleryZoomImageAria: "הגדלת תמונה",
    imageGalleryClickToZoom: "לחצו להגדלה",
    imageGalleryCloseAria: "סגור",
    imageGalleryPreviousAria: "תמונה קודמת",
    imageGalleryNextAria: "תמונה הבאה",
    imageGalleryProductImageAlt: "תמונת מוצר {index}",
    imageGalleryThumbnailAlt: "תמונה ממוזערת {index}",

    shippingFreeShippingUnlocked: "משלוח חינם הופעל!",
    shippingUnlockFreeShipping: "פתחו משלוח חינם",
    shippingFreeUnlocked: "משלוח חינם הופעל!",
    shippingUnlockFree: "פתחו משלוח חינם",
    shippingOnlyAway: "רק {amount} חסר",
    shippingViewCart: "צפייה בעגלה",
    shippingViewProducts: "צפייה במוצרים",
    freeShippingProgressUnlocked: "פתחתם משלוח חינם",
    freeShippingProgressRemaining: "הוסיפו עוד {amount} כדי לקבל משלוח חינם",
    freeShippingProgressThreshold: "סף: {amount} לפי סכום הביניים של הפריטים.",
    freeShippingProgressEligible: "זכאי",
    freeShippingProgressContinueShopping: "המשיכו לקנות כדי לפתוח זאת",

    recommendedSetupsQuickSwitch: "מעבר מהיר",
    recommendedSetupsTitle: "הגדרות מומלצות",
    recommendedSetupsDescription:
      "עברו בין שילובים מומלצים בלי לבחור מחדש כל אפשרות ידנית.",
    recommendedSetupsDefaultSetup: "הגדרת ברירת מחדל",
    recommendedSetupsRecommended: "מומלץ",
    recommendedSetupsCurrentSetup: "ההגדרה הנוכחית",
    recommendedSetupsUseDefaultSetup: "השתמשו בהגדרת ברירת המחדל",
    recommendedSetupsUseRecommendedSetup: "השתמשו בהגדרה המומלצת",
    recommendedSetupsViewThisSetup: "צפו בהגדרה הזו",
    recommendedSetupsPresetFallback: "הגדרה",
  },
}

const INTERPOLATION_PATTERN = /\{(\w+)\}/g

export const normalizeUiLocale = (locale: string | null | undefined): UiLocale => {
  const primary = locale?.split(/[-_]/)[0]?.toLowerCase()

  if (primary === "ar" || primary === "he") {
    return primary
  }

  return "en"
}

export const getUiCopy = (
  locale: string | null | undefined,
  key: UiCopyKey,
  params?: Record<string, string | number>
) => {
  const normalizedLocale = normalizeUiLocale(locale)
  const template =
    UI_COPY[normalizedLocale][key] ?? UI_COPY.en[key] ?? key

  if (!params) {
    return template
  }

  return template.replace(INTERPOLATION_PATTERN, (_, name: string) => {
    const value = params[name]
    return value === undefined || value === null ? "" : String(value)
  })
}

export type { UiCopyKey, UiLocale }