type AccountLocale = "en" | "ar" | "he"

const normalizeAccountLocale = (locale: string | null | undefined): AccountLocale => {
  const primary = locale?.split(/[-_]/)[0]?.toLowerCase()
  if (primary === "ar" || primary === "he") {
    return primary
  }
  return "en"
}

const ACCOUNT_COPY = {
  en: {
    account: "Account",
    myAccount: "My Account",
    overview: "Overview",
    profile: "Profile",
    addresses: "Addresses",
    orders: "Orders",
    logOut: "Log out",
    helloUser: "Hello, {name}!",
    signedInAs: "Signed in as:",
    profileCompletion: "Profile Completion",
    completed: "completed",
    savedAddresses: "Saved Addresses",
    saved: "saved",
    recentOrders: "Recent Orders",
    noRecentOrders: "No recent orders",
    datePlaced: "Date placed",
    orderNumber: "Order number",
    total: "Total",
    noOrdersYet: "No orders yet",
    noOrdersCta: "You don't have any orders yet - let's change that!",
    startShopping: "Start shopping ->",
    item: "item",
    items: "items",
    more: "more",
    seeDetails: "See details ->",
    profileTitle: "Profile",
    profileDescription:
      "View and update your profile information, including your name, email, and phone number.",
    shippingAddressesTitle: "Shipping Addresses",
    shippingAddressesDescription:
      "View and update your shipping addresses. Saving your addresses will make them available during checkout.",
    ordersTitle: "Orders",
    ordersDescription:
      "View your previous orders and their status. You can also create returns or exchanges for your orders if needed.",
    edit: "Edit",
    cancel: "Cancel",
    saveChanges: "Save changes",
    updatedSuccessfully: "{label} updated successfully",
    genericError: "An error occurred, please try again",
    name: "Name",
    email: "Email",
    phone: "Phone",
    password: "Password",
    signIn: "Sign in",
    notMember: "Not a member?",
    joinUs: "Join us",
    billingAddress: "Billing address",
    firstName: "First name",
    lastName: "Last name",
    company: "Company",
    address: "Address",
    apartment: "Apartment, suite, etc.",
    postalCode: "Postal code",
    city: "City",
    province: "Province",
    noBillingAddress: "No billing address",
    newAddress: "New address",
    addAddress: "Add address",
    editAddress: "Edit address",
    remove: "Remove",
    save: "Save",
    provinceState: "Province / State",
    orderTransfers: "Order transfers",
    transferMissingOrder: "Can't find the order you are looking for?",
    transferConnectOrder: "Connect an order to your account.",
    orderIdPlaceholder: "Order ID",
    requestTransfer: "Request transfer",
    transferRequested: "Transfer for order {id} requested",
    transferEmailSent: "Transfer request email sent to {email}",
    createYourAccount: "Create your account",
    loginWelcomeBack: "Welcome back",
    loginIntro:
      "Sign in to track orders and enjoy a faster checkout.",
    registerIntro: "Join us for a smarter, faster shopping experience.",
    loginTabSignIn: "Sign in",
    loginTabCreateAccount: "Create account",
    featureOrderTracking: "Order tracking",
    featureSavedAddresses: "Saved addresses",
    featureFastCheckout: "Fast checkout",
    createAccount: "Create account",
    alreadyMember: "Already a member?",
    byCreatingAccount: "By creating an account, you agree to our",
    privacyPolicy: "Privacy Policy",
    termsOfUse: "Terms of Use",
    and: "and",
    passwordNotShown: "The password is not shown for security reasons",
    oldPassword: "Old password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    passwordUpdateNotImplemented: "Password update is not implemented yet",
    metaSignInTitle: "Sign in",
    metaSignInDescription: "Sign in to your account.",
    metaAccountTitle: "Account",
    metaAccountDescription: "Overview of your account activity.",
    metaAddressesTitle: "Addresses",
    metaAddressesDescription: "View and manage your saved addresses.",
    metaOrdersTitle: "Orders",
    metaOrdersDescription: "Overview of your previous orders.",
    metaProfileTitle: "Profile",
    metaProfileDescription: "View and edit your profile information.",
    metaOrderTitle: "Order #{id}",
    metaOrderDescription: "View your order details.",
    metaOrderConfirmedTitle: "Order confirmed",
    metaOrderConfirmedDescription: "Your purchase was successful.",
    orderDetailsTitle: "Order details",
    backToOverview: "Back to overview",
    orderConfirmationSentTo: "We have sent the order confirmation details to",
    orderDate: "Order date",
    orderOfflinePaymentNotice:
      "Payment for this order will be arranged offline after confirmation.",
    orderStatus: "Order status",
    paymentStatus: "Payment",
    deliveryTitle: "Delivery",
    shippingAddress: "Shipping Address",
    contact: "Contact",
    method: "Method",
    orderSummaryTitle: "Order Summary",
    subtotal: "Subtotal",
    discount: "Discount",
    giftCard: "Gift card",
    shipping: "Shipping",
    taxes: "Taxes",
    needHelp: "Need help?",
    contactSupport: "Contact support",
    returnsExchanges: "Returns & Exchanges",
    statusPending: "Pending",
    statusNotPaid: "Not paid",
    statusAwaiting: "Awaiting",
    statusAuthorized: "Authorized",
    statusCaptured: "Captured",
    statusPartiallyCaptured: "Partially captured",
    statusRefunded: "Refunded",
    statusPartiallyRefunded: "Partially refunded",
    statusCanceled: "Canceled",
    statusNotFulfilled: "Not fulfilled",
    statusPartiallyFulfilled: "Partially fulfilled",
    statusFulfilled: "Fulfilled",
    statusPartiallyShipped: "Partially shipped",
    statusShipped: "Shipped",
    statusDelivered: "Delivered",
    statusRequiresAction: "Requires action",
    orderConfirmedThankYou: "Thank you! 🎉",
    orderConfirmedPlacedSuccessfully: "Your order was placed successfully.",
    orderConfirmedSummaryTitle: "Summary",
    orderConfirmedPaymentTitle: "Payment",
    orderConfirmedPaymentMethod: "Payment method",
    orderConfirmedPaymentDetails: "Payment details",
    orderConfirmedOfflinePaymentDetail:
      "No online payment was captured. Collect payment offline after order confirmation.",
    orderConfirmedPaidAt: "{amount} paid at {date}",
    orderConfirmedOnboardingTitle: "Your test order was successfully created! 🎉",
    orderConfirmedOnboardingDescription:
      "You can now complete setting up your store in the admin.",
    orderConfirmedOnboardingCta: "Complete setup in admin",
    orderTransferRequestTitle: "Transfer request for order {id}",
    orderTransferRequestDescription:
      "You've received a request to transfer ownership of your order ({id}). If you agree to this request, you can approve the transfer by clicking the button below.",
    orderTransferRequestAcceptConsequences:
      "If you accept, the new owner will take over all responsibilities and permissions associated with this order.",
    orderTransferRequestNoAction:
      "If you do not recognize this request or wish to retain ownership, no further action is required.",
    orderTransferAcceptButton: "Accept transfer",
    orderTransferDeclineButton: "Decline transfer",
    orderTransferAcceptedInline: "Order transferred successfully!",
    orderTransferDeclinedInline: "Order transfer declined successfully!",
    orderTransferAcceptedTitle: "Order transferred!",
    orderTransferAcceptedDescription:
      "Order {id} has been successfully transferred to the new owner.",
    orderTransferAcceptError:
      "There was an error accepting the transfer. Please try again.",
    orderTransferDeclinedTitle: "Order transfer declined!",
    orderTransferDeclinedDescription:
      "Transfer of order {id} has been successfully declined.",
    orderTransferDeclineError:
      "There was an error declining the transfer. Please try again.",
    orderTransferErrorMessage: "Error message: {error}",
  },
  ar: {
    account: "الحساب",
    myAccount: "حسابي",
    overview: "نظرة عامة",
    profile: "الملف الشخصي",
    addresses: "العناوين",
    orders: "الطلبات",
    logOut: "تسجيل الخروج",
    helloUser: "مرحباً، {name}!",
    signedInAs: "مسجل الدخول باسم:",
    profileCompletion: "اكتمال الملف الشخصي",
    completed: "مكتمل",
    savedAddresses: "العناوين المحفوظة",
    saved: "محفوظ",
    recentOrders: "الطلبات الأخيرة",
    noRecentOrders: "لا توجد طلبات حديثة",
    datePlaced: "تاريخ الطلب",
    orderNumber: "رقم الطلب",
    total: "الإجمالي",
    noOrdersYet: "لا توجد طلبات بعد",
    noOrdersCta: "ليس لديك أي طلبات بعد - لنبدأ التسوق!",
    startShopping: "ابدأ التسوق ->",
    item: "عنصر",
    items: "عناصر",
    more: "أكثر",
    seeDetails: "عرض التفاصيل ->",
    profileTitle: "الملف الشخصي",
    profileDescription:
      "اعرض وحدث معلومات ملفك الشخصي، بما في ذلك الاسم والبريد الإلكتروني ورقم الهاتف.",
    shippingAddressesTitle: "عناوين الشحن",
    shippingAddressesDescription:
      "اعرض وحدث عناوين الشحن الخاصة بك. حفظ العناوين يجعلها متاحة أثناء الدفع.",
    ordersTitle: "الطلبات",
    ordersDescription:
      "اعرض طلباتك السابقة وحالتها. يمكنك أيضاً إنشاء طلبات إرجاع أو استبدال عند الحاجة.",
    edit: "تعديل",
    cancel: "إلغاء",
    saveChanges: "حفظ التغييرات",
    updatedSuccessfully: "تم تحديث {label} بنجاح",
    genericError: "حدث خطأ، حاول مرة أخرى",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    password: "كلمة المرور",
    signIn: "تسجيل الدخول",
    notMember: "لست عضوا؟",
    joinUs: "انضم إلينا",
    billingAddress: "عنوان الفوترة",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    company: "الشركة",
    address: "العنوان",
    apartment: "الشقة، الجناح، إلخ",
    postalCode: "الرمز البريدي",
    city: "المدينة",
    province: "المنطقة",
    noBillingAddress: "لا يوجد عنوان فوترة",
    newAddress: "عنوان جديد",
    addAddress: "إضافة عنوان",
    editAddress: "تعديل العنوان",
    remove: "إزالة",
    save: "حفظ",
    provinceState: "المنطقة / الولاية",
    orderTransfers: "نقل الطلبات",
    transferMissingOrder: "لا تجد الطلب الذي تبحث عنه؟",
    transferConnectOrder: "اربط طلبا بحسابك.",
    orderIdPlaceholder: "رقم الطلب",
    requestTransfer: "طلب النقل",
    transferRequested: "تم طلب نقل الطلب {id}",
    transferEmailSent: "تم إرسال بريد طلب النقل إلى {email}",
    createYourAccount: "أنشئ حسابك",
    loginWelcomeBack: "مرحباً بعودتك",
    loginIntro: "سجل الدخول لتتبع الطلبات والاستمتاع بدفع أسرع.",
    registerIntro: "انضم إلينا لتجربة تسوق أذكى وأسرع.",
    loginTabSignIn: "تسجيل الدخول",
    loginTabCreateAccount: "إنشاء حساب",
    featureOrderTracking: "تتبع الطلبات",
    featureSavedAddresses: "العناوين المحفوظة",
    featureFastCheckout: "دفع سريع",
    createAccount: "إنشاء حساب",
    alreadyMember: "لديك حساب بالفعل؟",
    byCreatingAccount: "بإنشاء حساب، فإنك توافق على",
    privacyPolicy: "سياسة الخصوصية",
    termsOfUse: "شروط الاستخدام",
    and: "و",
    passwordNotShown: "لا يتم عرض كلمة المرور لأسباب أمنية",
    oldPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    passwordUpdateNotImplemented: "تحديث كلمة المرور غير متاح بعد",
    metaSignInTitle: "تسجيل الدخول",
    metaSignInDescription: "سجل الدخول إلى حسابك.",
    metaAccountTitle: "الحساب",
    metaAccountDescription: "نظرة عامة على نشاط حسابك.",
    metaAddressesTitle: "العناوين",
    metaAddressesDescription: "عرض وإدارة العناوين المحفوظة.",
    metaOrdersTitle: "الطلبات",
    metaOrdersDescription: "نظرة عامة على طلباتك السابقة.",
    metaProfileTitle: "الملف الشخصي",
    metaProfileDescription: "عرض وتعديل معلومات ملفك الشخصي.",
    metaOrderTitle: "الطلب #{id}",
    metaOrderDescription: "عرض تفاصيل طلبك.",
    metaOrderConfirmedTitle: "تم تأكيد الطلب",
    metaOrderConfirmedDescription: "تمت عملية الشراء بنجاح.",
    orderDetailsTitle: "تفاصيل الطلب",
    backToOverview: "العودة إلى نظرة عامة الطلبات",
    orderConfirmationSentTo: "لقد أرسلنا تفاصيل تأكيد الطلب إلى",
    orderDate: "تاريخ الطلب",
    orderOfflinePaymentNotice:
      "سيتم ترتيب الدفع لهذا الطلب بشكل غير متصل بعد التأكيد.",
    orderStatus: "حالة الطلب",
    paymentStatus: "الدفع",
    deliveryTitle: "التوصيل",
    shippingAddress: "عنوان الشحن",
    contact: "بيانات التواصل",
    method: "الطريقة",
    orderSummaryTitle: "ملخص الطلب",
    subtotal: "الإجمالي الفرعي",
    discount: "الخصم",
    giftCard: "بطاقة هدية",
    shipping: "الشحن",
    taxes: "الضرائب",
    needHelp: "هل تحتاج إلى مساعدة؟",
    contactSupport: "تواصل مع الدعم",
    returnsExchanges: "الإرجاع والاستبدال",
    statusPending: "قيد الانتظار",
    statusNotPaid: "غير مدفوع",
    statusAwaiting: "بانتظار المعالجة",
    statusAuthorized: "مفوض",
    statusCaptured: "تم التحصيل",
    statusPartiallyCaptured: "تم التحصيل جزئيا",
    statusRefunded: "تم الاسترداد",
    statusPartiallyRefunded: "تم الاسترداد جزئيا",
    statusCanceled: "ملغي",
    statusNotFulfilled: "غير منفذ",
    statusPartiallyFulfilled: "منفذ جزئيا",
    statusFulfilled: "منفذ",
    statusPartiallyShipped: "تم الشحن جزئيا",
    statusShipped: "تم الشحن",
    statusDelivered: "تم التسليم",
    statusRequiresAction: "يتطلب إجراء",
    orderConfirmedThankYou: "شكرا لك! 🎉",
    orderConfirmedPlacedSuccessfully: "تم إنشاء طلبك بنجاح.",
    orderConfirmedSummaryTitle: "الملخص",
    orderConfirmedPaymentTitle: "الدفع",
    orderConfirmedPaymentMethod: "طريقة الدفع",
    orderConfirmedPaymentDetails: "تفاصيل الدفع",
    orderConfirmedOfflinePaymentDetail:
      "لم يتم تحصيل أي دفعة إلكترونية. يتم تحصيل الدفع لاحقا بعد تأكيد الطلب.",
    orderConfirmedPaidAt: "تم دفع {amount} في {date}",
    orderConfirmedOnboardingTitle: "تم إنشاء طلبك التجريبي بنجاح! 🎉",
    orderConfirmedOnboardingDescription:
      "يمكنك الآن إكمال إعداد متجرك من لوحة الإدارة.",
    orderConfirmedOnboardingCta: "إكمال الإعداد في لوحة الإدارة",
    orderTransferRequestTitle: "طلب نقل للطلب {id}",
    orderTransferRequestDescription:
      "لقد وصلك طلب لنقل ملكية طلبك ({id}). إذا كنت توافق على هذا الطلب، يمكنك الموافقة على النقل بالنقر على الزر أدناه.",
    orderTransferRequestAcceptConsequences:
      "إذا وافقت، فسيتولى المالك الجديد جميع المسؤوليات والصلاحيات المرتبطة بهذا الطلب.",
    orderTransferRequestNoAction:
      "إذا كنت لا تتعرف على هذا الطلب أو ترغب في الاحتفاظ بالملكية، فلا حاجة إلى أي إجراء إضافي.",
    orderTransferAcceptButton: "قبول النقل",
    orderTransferDeclineButton: "رفض النقل",
    orderTransferAcceptedInline: "تم نقل الطلب بنجاح!",
    orderTransferDeclinedInline: "تم رفض نقل الطلب بنجاح!",
    orderTransferAcceptedTitle: "تم نقل الطلب!",
    orderTransferAcceptedDescription:
      "تم نقل الطلب {id} بنجاح إلى المالك الجديد.",
    orderTransferAcceptError:
      "حدث خطأ أثناء قبول النقل. يرجى المحاولة مرة أخرى.",
    orderTransferDeclinedTitle: "تم رفض نقل الطلب!",
    orderTransferDeclinedDescription:
      "تم رفض نقل الطلب {id} بنجاح.",
    orderTransferDeclineError:
      "حدث خطأ أثناء رفض النقل. يرجى المحاولة مرة أخرى.",
    orderTransferErrorMessage: "رسالة الخطأ: {error}",
  },
  he: {
    account: "חשבון",
    myAccount: "החשבון שלי",
    overview: "סקירה כללית",
    profile: "פרופיל",
    addresses: "כתובות",
    orders: "הזמנות",
    logOut: "התנתקות",
    helloUser: "שלום, {name}!",
    signedInAs: "מחובר כ:",
    profileCompletion: "השלמת פרופיל",
    completed: "הושלם",
    savedAddresses: "כתובות שמורות",
    saved: "שמורות",
    recentOrders: "הזמנות אחרונות",
    noRecentOrders: "אין הזמנות אחרונות",
    datePlaced: "תאריך הזמנה",
    orderNumber: "מספר הזמנה",
    total: "סה\"כ",
    noOrdersYet: "אין הזמנות עדיין",
    noOrdersCta: "עדיין אין לך הזמנות - בואו נשנה את זה!",
    startShopping: "התחל לקנות ->",
    item: "פריט",
    items: "פריטים",
    more: "נוספים",
    seeDetails: "צפייה בפרטים ->",
    profileTitle: "פרופיל",
    profileDescription:
      "צפו ועדכנו את פרטי הפרופיל שלכם, כולל שם, אימייל ומספר טלפון.",
    shippingAddressesTitle: "כתובות משלוח",
    shippingAddressesDescription:
      "צפו ועדכנו את כתובות המשלוח שלכם. שמירת כתובות תאפשר שימוש בהן בקופה.",
    ordersTitle: "הזמנות",
    ordersDescription:
      "צפו בהזמנות הקודמות ובסטטוס שלהן. ניתן גם לבקש החזרה או החלפה במידת הצורך.",
    edit: "עריכה",
    cancel: "ביטול",
    saveChanges: "שמירת שינויים",
    updatedSuccessfully: "{label} עודכן בהצלחה",
    genericError: "אירעה שגיאה, נסו שוב",
    name: "שם",
    email: "אימייל",
    phone: "טלפון",
    password: "סיסמה",
    signIn: "התחברות",
    notMember: "עדיין לא חבר?",
    joinUs: "הצטרפו אלינו",
    billingAddress: "כתובת חיוב",
    firstName: "שם פרטי",
    lastName: "שם משפחה",
    company: "חברה",
    address: "כתובת",
    apartment: "דירה, סוויטה וכו'",
    postalCode: "מיקוד",
    city: "עיר",
    province: "מחוז",
    noBillingAddress: "אין כתובת חיוב",
    newAddress: "כתובת חדשה",
    addAddress: "הוספת כתובת",
    editAddress: "עריכת כתובת",
    remove: "הסר",
    save: "שמור",
    provinceState: "מחוז / מדינה",
    orderTransfers: "העברות הזמנה",
    transferMissingOrder: "לא מוצאים את ההזמנה שחיפשתם?",
    transferConnectOrder: "חברו הזמנה לחשבון שלכם.",
    orderIdPlaceholder: "מספר הזמנה",
    requestTransfer: "בקשת העברה",
    transferRequested: "הועברה בקשה להעברת הזמנה {id}",
    transferEmailSent: "מייל בקשת העברה נשלח אל {email}",
    createYourAccount: "צור את החשבון שלך",
    loginWelcomeBack: "ברוכים השבים",
    loginIntro: "התחברו כדי לעקוב אחרי הזמנות וליהנות מקופה מהירה יותר.",
    registerIntro: "הצטרפו לחוויית קנייה חכמה ומהירה יותר.",
    loginTabSignIn: "התחברות",
    loginTabCreateAccount: "יצירת חשבון",
    featureOrderTracking: "מעקב הזמנות",
    featureSavedAddresses: "כתובות שמורות",
    featureFastCheckout: "קופה מהירה",
    createAccount: "יצירת חשבון",
    alreadyMember: "כבר חברים?",
    byCreatingAccount: "ביצירת חשבון אתם מסכימים ל",
    privacyPolicy: "מדיניות הפרטיות",
    termsOfUse: "תנאי השימוש",
    and: "ו",
    passwordNotShown: "הסיסמה לא מוצגת מטעמי אבטחה",
    oldPassword: "סיסמה נוכחית",
    newPassword: "סיסמה חדשה",
    confirmPassword: "אישור סיסמה",
    passwordUpdateNotImplemented: "עדכון סיסמה עדיין לא נתמך",
    metaSignInTitle: "התחברות",
    metaSignInDescription: "התחברו לחשבון שלכם.",
    metaAccountTitle: "חשבון",
    metaAccountDescription: "סקירה כללית של פעילות החשבון שלכם.",
    metaAddressesTitle: "כתובות",
    metaAddressesDescription: "צפייה וניהול הכתובות השמורות שלכם.",
    metaOrdersTitle: "הזמנות",
    metaOrdersDescription: "סקירה כללית של ההזמנות הקודמות שלכם.",
    metaProfileTitle: "פרופיל",
    metaProfileDescription: "צפייה ועריכה של פרטי הפרופיל שלכם.",
    metaOrderTitle: "הזמנה #{id}",
    metaOrderDescription: "צפו בפרטי ההזמנה שלכם.",
    metaOrderConfirmedTitle: "ההזמנה אושרה",
    metaOrderConfirmedDescription: "הרכישה שלכם הושלמה בהצלחה.",
    orderDetailsTitle: "פרטי הזמנה",
    backToOverview: "חזרה לסקירת ההזמנות",
    orderConfirmationSentTo: "שלחנו את פרטי אישור ההזמנה אל",
    orderDate: "תאריך הזמנה",
    orderOfflinePaymentNotice:
      "התשלום עבור הזמנה זו יוסדר באופן לא מקוון לאחר האישור.",
    orderStatus: "סטטוס הזמנה",
    paymentStatus: "תשלום",
    deliveryTitle: "משלוח",
    shippingAddress: "כתובת משלוח",
    contact: "פרטי קשר",
    method: "שיטה",
    orderSummaryTitle: "סיכום הזמנה",
    subtotal: "סכום ביניים",
    discount: "הנחה",
    giftCard: "כרטיס מתנה",
    shipping: "משלוח",
    taxes: "מסים",
    needHelp: "צריכים עזרה?",
    contactSupport: "יצירת קשר עם התמיכה",
    returnsExchanges: "החזרות והחלפות",
    statusPending: "ממתין",
    statusNotPaid: "לא שולם",
    statusAwaiting: "ממתין לטיפול",
    statusAuthorized: "אושר",
    statusCaptured: "נגבה",
    statusPartiallyCaptured: "נגבה חלקית",
    statusRefunded: "הוחזר",
    statusPartiallyRefunded: "הוחזר חלקית",
    statusCanceled: "בוטל",
    statusNotFulfilled: "לא סופק",
    statusPartiallyFulfilled: "סופק חלקית",
    statusFulfilled: "סופק",
    statusPartiallyShipped: "נשלח חלקית",
    statusShipped: "נשלח",
    statusDelivered: "נמסר",
    statusRequiresAction: "נדרשת פעולה",
    orderConfirmedThankYou: "תודה רבה! 🎉",
    orderConfirmedPlacedSuccessfully: "ההזמנה שלכם בוצעה בהצלחה.",
    orderConfirmedSummaryTitle: "סיכום",
    orderConfirmedPaymentTitle: "תשלום",
    orderConfirmedPaymentMethod: "אמצעי תשלום",
    orderConfirmedPaymentDetails: "פרטי תשלום",
    orderConfirmedOfflinePaymentDetail:
      "לא בוצע חיוב מקוון. גביית התשלום תיעשה לא מקוון לאחר אישור ההזמנה.",
    orderConfirmedPaidAt: "שולם {amount} בתאריך {date}",
    orderConfirmedOnboardingTitle: "הזמנת הבדיקה שלכם נוצרה בהצלחה! 🎉",
    orderConfirmedOnboardingDescription:
      "עכשיו אפשר להשלים את הגדרת החנות דרך ממשק הניהול.",
    orderConfirmedOnboardingCta: "השלמת ההגדרה בממשק הניהול",
    orderTransferRequestTitle: "בקשת העברה עבור הזמנה {id}",
    orderTransferRequestDescription:
      "קיבלתם בקשה להעברת הבעלות על ההזמנה שלכם ({id}). אם אתם מסכימים לבקשה הזו, אפשר לאשר את ההעברה בלחיצה על הכפתור למטה.",
    orderTransferRequestAcceptConsequences:
      "אם תאשרו, הבעלים החדש יקבל את כל האחריות וההרשאות הקשורות להזמנה הזו.",
    orderTransferRequestNoAction:
      "אם אינכם מזהים את הבקשה הזו או רוצים לשמור על הבעלות, אין צורך בפעולה נוספת.",
    orderTransferAcceptButton: "אישור העברה",
    orderTransferDeclineButton: "דחיית העברה",
    orderTransferAcceptedInline: "ההזמנה הועברה בהצלחה!",
    orderTransferDeclinedInline: "העברת ההזמנה נדחתה בהצלחה!",
    orderTransferAcceptedTitle: "ההזמנה הועברה!",
    orderTransferAcceptedDescription:
      "הזמנה {id} הועברה בהצלחה לבעלים החדש.",
    orderTransferAcceptError:
      "אירעה שגיאה בעת אישור ההעברה. נסו שוב.",
    orderTransferDeclinedTitle: "העברת ההזמנה נדחתה!",
    orderTransferDeclinedDescription:
      "העברת ההזמנה {id} נדחתה בהצלחה.",
    orderTransferDeclineError:
      "אירעה שגיאה בעת דחיית ההעברה. נסו שוב.",
    orderTransferErrorMessage: "הודעת שגיאה: {error}",
  },
} as const

type AccountCopyKey = keyof (typeof ACCOUNT_COPY)["en"]

export const getAccountCopy = (
  locale: string | null | undefined,
  key: AccountCopyKey,
  params?: Record<string, string | number>
) => {
  const normalized = normalizeAccountLocale(locale)
  const template = ACCOUNT_COPY[normalized][key] ?? ACCOUNT_COPY.en[key] ?? key

  if (!params) {
    return template
  }

  return template.replace(/\{(\w+)\}/g, (_, name: string) =>
    params[name] === undefined ? "" : String(params[name])
  )
}
